
# This file is automatically generated, you probably don't want to edit this

bootrestscoreOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            iterations = 200,
            samplesize = 600,
            cutoff = 67,
            seed = 42,
            showPlot = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="bootrestscore",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=200,
                min=50)
            private$..samplesize <- jmvcore::OptionInteger$new(
                "samplesize",
                samplesize,
                default=600,
                min=30)
            private$..cutoff <- jmvcore::OptionNumber$new(
                "cutoff",
                cutoff,
                default=67,
                min=0,
                max=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..iterations)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..cutoff)
            self$.addOption(private$..seed)
            self$.addOption(private$..showPlot)
        }),
    active = list(
        vars = function() private$..vars$value,
        iterations = function() private$..iterations$value,
        samplesize = function() private$..samplesize$value,
        cutoff = function() private$..cutoff$value,
        seed = function() private$..seed$value,
        showPlot = function() private$..showPlot$value),
    private = list(
        ..vars = NA,
        ..iterations = NA,
        ..samplesize = NA,
        ..cutoff = NA,
        ..seed = NA,
        ..showPlot = NA)
)

bootrestscoreResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreResults",
    inherit = jmvcore::Group,
    active = list(
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        bootstrapNote = function() private$.items[["bootstrapNote"]],
        bootstrapPlot = function() private$.items[["bootstrapPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrap Item-Restscore")
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Item-Restscore Misfit",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "kreiner2011",
                    "mueller2022",
                    "mair2007",
                    "zeileis2026",
                    "johansson2025_detecting"),
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed",
                    "cutoff"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="pctOverfit", 
                        `title`="% Overfit", 
                        `type`="number"),
                    list(
                        `name`="pctUnderfit", 
                        `title`="% Underfit", 
                        `type`="number"),
                    list(
                        `name`="pctNoMisfit", 
                        `title`="% No misfit", 
                        `type`="number"),
                    list(
                        `name`="infitMSQ", 
                        `title`="Cond. infit MSQ", 
                        `type`="number"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="bootstrapNote",
                title="",
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed",
                    "cutoff")))
            self$add(jmvcore::Image$new(
                options=options,
                name="bootstrapPlot",
                title="Bootstrap Classification Percentages",
                width=600,
                height=500,
                renderFun=".bootstrapPlot",
                visible="(showPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed",
                    "cutoff")))}))

bootrestscoreBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "bootrestscore",
                version = c(1,0,0),
                options = options,
                results = bootrestscoreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrap Item-Restscore
#'
#' Non-parametric bootstrap of item-restscore fit using 
#' iarm::item_restscore().
#' For each iteration a sample of size \code{samplesize} is drawn from the 
#' data
#' with replacement, the appropriate Rasch model (eRm::RM for dichotomous,
#' psychotools::pcmodel for polytomous) is refitted, and items are classified
#' as overfit, underfit, or no misfit based on the BH-adjusted p-value
#' (< .05) and the sign of (expected - observed). Useful with large samples
#' where the asymptotic test can flag items that are not practically
#' misfitting.
#' 
#' @param data .
#' @param vars .
#' @param iterations .
#' @param samplesize .
#' @param cutoff .
#' @param seed .
#' @param showPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bootstrapNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$bootstrapPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$bootstrapTable$asDF}
#'
#' \code{as.data.frame(results$bootstrapTable)}
#'
#' @export
bootrestscore <- function(
    data,
    vars,
    iterations = 200,
    samplesize = 600,
    cutoff = 67,
    seed = 42,
    showPlot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootrestscore requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- bootrestscoreOptions$new(
        vars = vars,
        iterations = iterations,
        samplesize = samplesize,
        cutoff = cutoff,
        seed = seed,
        showPlot = showPlot)

    analysis <- bootrestscoreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

