
# This file is automatically generated, you probably don't want to edit this

bootrestscoreOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            iterations = 250,
            samplesize = 600,
            cutoff = 67,
            seed = 42,
            sortBy = "none",
            showPlot = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="bootrestscore",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=250,
                min=50,
                max=5000)
            private$..samplesize <- jmvcore::OptionInteger$new(
                "samplesize",
                samplesize,
                default=600,
                min=30)
            private$..cutoff <- jmvcore::OptionNumber$new(
                "cutoff",
                cutoff,
                default=67,
                min=0,
                max=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..sortBy <- jmvcore::OptionList$new(
                "sortBy",
                sortBy,
                options=list(
                    "none",
                    "overfit",
                    "underfit"),
                default="none")
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..iterations)
            self$.addOption(private$..samplesize)
            self$.addOption(private$..cutoff)
            self$.addOption(private$..seed)
            self$.addOption(private$..sortBy)
            self$.addOption(private$..showPlot)
        }),
    active = list(
        vars = function() private$..vars$value,
        iterations = function() private$..iterations$value,
        samplesize = function() private$..samplesize$value,
        cutoff = function() private$..cutoff$value,
        seed = function() private$..seed$value,
        sortBy = function() private$..sortBy$value,
        showPlot = function() private$..showPlot$value),
    private = list(
        ..vars = NA,
        ..iterations = NA,
        ..samplesize = NA,
        ..cutoff = NA,
        ..seed = NA,
        ..sortBy = NA,
        ..showPlot = NA)
)

bootrestscoreResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreResults",
    inherit = jmvcore::Group,
    active = list(
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        simCache = function() private$.items[["simCache"]],
        bootstrapNote = function() private$.items[["bootstrapNote"]],
        bootstrapPlot = function() private$.items[["bootstrapPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrap Item-Restscore")
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Item-Restscore Misfit",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "kreiner2011",
                    "mueller2022",
                    "zeileis2026",
                    "warm1989",
                    "johansson2025_detecting"),
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed",
                    "cutoff",
                    "sortBy"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="pctOverfit", 
                        `title`="% Overfit", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pctUnderfit", 
                        `title`="% Underfit", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="misfit", 
                        `title`="Flagged", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="simCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="bootstrapNote",
                title="",
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="bootstrapPlot",
                title="Bootstrap Item-Restscore Differences",
                width=500,
                height=600,
                renderFun=".bootstrapPlot",
                visible="(showPlot)",
                clearWith=list(
                    "vars",
                    "iterations",
                    "samplesize",
                    "seed",
                    "sortBy")))}))

bootrestscoreBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootrestscoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "bootrestscore",
                version = c(1,0,0),
                options = options,
                results = bootrestscoreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrap Item-Restscore
#'
#' Non-parametric bootstrap of item-restscore fit via the easyRasch2 R
#' package (RMitemRestscoreBoot). For each iteration a sample of size
#' \code{samplesize} is drawn from the data with replacement, the Rasch /
#' Partial Credit model is refitted by conditional maximum likelihood
#' (psychotools::pcmodel), and items are classified as overfit,
#' underfit, or no misfit based on the BH-adjusted p-value (< .05) from
#' iarm::item_restscore() and the sign of (observed - expected). Useful
#' with large samples where the asymptotic test can flag items that are
#' not practically misfitting. The bootstrap is numerically identical
#' to easyRasch2::RMitemRestscoreBoot() with the same seed and
#' iterations. Single-core sequential processing is used.
#' 
#' @param data .
#' @param vars .
#' @param iterations .
#' @param samplesize .
#' @param cutoff .
#' @param seed .
#' @param sortBy .
#' @param showPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$simCache} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$bootstrapNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$bootstrapPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$bootstrapTable$asDF}
#'
#' \code{as.data.frame(results$bootstrapTable)}
#'
#' @export
bootrestscore <- function(
    data,
    vars,
    iterations = 250,
    samplesize = 600,
    cutoff = 67,
    seed = 42,
    sortBy = "none",
    showPlot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootrestscore requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- bootrestscoreOptions$new(
        vars = vars,
        iterations = iterations,
        samplesize = samplesize,
        cutoff = cutoff,
        seed = seed,
        sortBy = sortBy,
        showPlot = showPlot)

    analysis <- bootrestscoreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

