
# This file is automatically generated, you probably don't want to edit this

cfacutoffOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cfacutoffOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            estimator = "WLSMV",
            percentile = 99,
            iterations = 250,
            seed = 42, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="cfacutoff",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "WLSMV",
                    "ULSMV"),
                default="WLSMV")
            private$..percentile <- jmvcore::OptionNumber$new(
                "percentile",
                percentile,
                default=99,
                min=50,
                max=99.9)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=250,
                min=50,
                max=5000)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)

            self$.addOption(private$..vars)
            self$.addOption(private$..estimator)
            self$.addOption(private$..percentile)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
        }),
    active = list(
        vars = function() private$..vars$value,
        estimator = function() private$..estimator$value,
        percentile = function() private$..percentile$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value),
    private = list(
        ..vars = NA,
        ..estimator = NA,
        ..percentile = NA,
        ..iterations = NA,
        ..seed = NA)
)

cfacutoffResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cfacutoffResults",
    inherit = jmvcore::Group,
    active = list(
        cfaTable = function() private$.items[["cfaTable"]],
        loadingsTable = function() private$.items[["loadingsTable"]],
        cfaNote = function() private$.items[["cfaNote"]],
        cfaPlot = function() private$.items[["cfaPlot"]],
        cfaLoadingsPlot = function() private$.items[["cfaLoadingsPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dynamic CFA Fit-Index Cutoffs")
            self$add(jmvcore::Table$new(
                options=options,
                name="cfaTable",
                title="Observed CFA Fit vs Simulated Cutoff",
                rows=3,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "zeileis2026",
                    "warm1989"),
                clearWith=list(
                    "vars",
                    "estimator",
                    "percentile",
                    "iterations",
                    "seed"),
                columns=list(
                    list(
                        `name`="index", 
                        `title`="Index", 
                        `type`="text"),
                    list(
                        `name`="observed", 
                        `title`="Observed", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cutoff", 
                        `title`="Cutoff", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="loadingsTable",
                title="Standardized Loadings vs Simulated Expected Range",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "estimator",
                    "percentile",
                    "iterations",
                    "seed"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="observed", 
                        `title`="Observed loading", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="low", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="high", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="cfaNote",
                title="",
                clearWith=list(
                    "vars",
                    "estimator",
                    "percentile",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="cfaPlot",
                title="Observed CFA Fit vs Simulated Null Distribution",
                width=700,
                height=350,
                renderFun=".cfaPlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "estimator",
                    "percentile",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="cfaLoadingsPlot",
                title="Standardized Loadings vs Simulated Expected Range",
                width=600,
                height=500,
                renderFun=".cfaLoadingsPlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "estimator",
                    "percentile",
                    "iterations",
                    "seed")))}))

cfacutoffBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cfacutoffBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "cfacutoff",
                version = c(1,0,0),
                options = options,
                results = cfacutoffResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Dynamic CFA Fit-Index Cutoffs
#'
#' Tests whether the observed one-factor categorical-CFA fit indices
#' (CFI, RMSEA, SRMR) are consistent with the data being generated by a
#' unidimensional Rasch / Partial Credit Model, via the easyRasch2 R
#' package (results are identical to easyRasch2::RMdimCFACutoff() and
#' RMdimCFA() with the same seed). Datasets are simulated under the
#' fitted model (psychotools CML with WLE person estimates), refitted
#' with lavaan (ordered = TRUE), and the observed indices are compared
#' to percentile cutoffs from the simulated null distribution. Also
#' reports each item's observed standardized loading against its
#' simulated expected range, with figures for both views.
#' 
#' For each iteration a dataset is simulated from the fitted PCM
#' (or RM, for dichotomous data) using observed item parameters
#' and a resampled person distribution; lavaan::cfa(ordered = TRUE)
#' is fitted on the simulation and CFI / RMSEA / SRMR are recorded.
#' The result is a parametric-bootstrap null distribution against
#' which the observed fit indices are compared, one-sided in the
#' unfavourable direction (CFI from below; RMSEA / SRMR from
#' above).
#' 
#' Items are flagged when the observed value lies outside the
#' chosen percentile of the simulated distribution. At the default
#' 99th-percentile setting, an item is flagged when its observed
#' value is in the worst 1\% of the null distribution.
#' 
#' @param data .
#' @param vars .
#' @param estimator .
#' @param percentile .
#' @param iterations .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$cfaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$loadingsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cfaNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cfaPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cfaLoadingsPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cfaTable$asDF}
#'
#' \code{as.data.frame(results$cfaTable)}
#'
#' @export
cfacutoff <- function(
    data,
    vars,
    estimator = "WLSMV",
    percentile = 99,
    iterations = 250,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cfacutoff requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- cfacutoffOptions$new(
        vars = vars,
        estimator = estimator,
        percentile = percentile,
        iterations = iterations,
        seed = seed)

    analysis <- cfacutoffClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

