
# This file is automatically generated, you probably don't want to edit this

ciccOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ciccOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            difVar = NULL,
            method = "quantile",
            classIntervals = 4,
            ci = TRUE,
            errorBand = FALSE,
            confLevel = 95,
            minN = 8, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="cicc",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..difVar <- jmvcore::OptionVariable$new(
                "difVar",
                difVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "quantile",
                    "width",
                    "score"),
                default="quantile")
            private$..classIntervals <- jmvcore::OptionInteger$new(
                "classIntervals",
                classIntervals,
                default=4,
                min=2,
                max=10)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=TRUE)
            private$..errorBand <- jmvcore::OptionBool$new(
                "errorBand",
                errorBand,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95,
                min=50,
                max=99.9)
            private$..minN <- jmvcore::OptionInteger$new(
                "minN",
                minN,
                default=8,
                min=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..difVar)
            self$.addOption(private$..method)
            self$.addOption(private$..classIntervals)
            self$.addOption(private$..ci)
            self$.addOption(private$..errorBand)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..minN)
        }),
    active = list(
        vars = function() private$..vars$value,
        difVar = function() private$..difVar$value,
        method = function() private$..method$value,
        classIntervals = function() private$..classIntervals$value,
        ci = function() private$..ci$value,
        errorBand = function() private$..errorBand$value,
        confLevel = function() private$..confLevel$value,
        minN = function() private$..minN$value),
    private = list(
        ..vars = NA,
        ..difVar = NA,
        ..method = NA,
        ..classIntervals = NA,
        ..ci = NA,
        ..errorBand = NA,
        ..confLevel = NA,
        ..minN = NA)
)

ciccResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ciccResults",
    inherit = jmvcore::Group,
    active = list(
        ciccPlot = function() private$.items[["ciccPlot"]],
        ciccNote = function() private$.items[["ciccNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Item Characteristic Curves (CICC)")
            self$add(jmvcore::Image$new(
                options=options,
                name="ciccPlot",
                title="Conditional Item Characteristic Curves",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "buchardt2023",
                    "kreiner2011",
                    "christensen2013",
                    "zeileis2026",
                    "warm1989"),
                width=700,
                height=700,
                renderFun=".ciccPlot",
                clearWith=list(
                    "vars",
                    "difVar",
                    "method",
                    "classIntervals",
                    "ci",
                    "errorBand",
                    "confLevel",
                    "minN")))
            self$add(jmvcore::Html$new(
                options=options,
                name="ciccNote",
                title="",
                clearWith=list(
                    "vars",
                    "difVar",
                    "method",
                    "classIntervals",
                    "ci",
                    "errorBand",
                    "confLevel",
                    "minN")))}))

ciccBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ciccBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "cicc",
                version = c(1,0,0),
                options = options,
                results = ciccResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Item Characteristic Curves (CICC)
#'
#' Conditional item characteristic curves (Buchardt, Christensen &
#' Jensen, 2023): the model-expected item score as a function of the
#' total score (the exact conditional expectation), with observed mean
#' item scores overlaid per total-score group. Groups are formed on
#' the total-score scale -- quantile-based (approximately equal
#' numbers of respondents), equal-width score intervals, or one group
#' per total score -- and observed means that deviate from the
#' expected curve indicate localized item misfit. Drawn by
#' easyRasch2::RMitemICCPlot() (CML item estimation via psychotools).
#' 
#' When a DIF variable is supplied, observed averages are drawn
#' separately per group so group-specific deviations from the common
#' expected curve can be inspected; panels are annotated with the
#' partial-gamma DIF statistic.
#' 
#' @param data .
#' @param vars .
#' @param difVar .
#' @param method .
#' @param classIntervals .
#' @param ci .
#' @param errorBand .
#' @param confLevel .
#' @param minN .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ciccPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ciccNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
cicc <- function(
    data,
    vars,
    difVar = NULL,
    method = "quantile",
    classIntervals = 4,
    ci = TRUE,
    errorBand = FALSE,
    confLevel = 95,
    minN = 8) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cicc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(difVar)) difVar <- jmvcore::resolveQuo(jmvcore::enquo(difVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(difVar), difVar, NULL))

    for (v in difVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ciccOptions$new(
        vars = vars,
        difVar = difVar,
        method = method,
        classIntervals = classIntervals,
        ci = ci,
        errorBand = errorBand,
        confLevel = confLevel,
        minN = minN)

    analysis <- ciccClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

