
# This file is automatically generated, you probably don't want to edit this

diftreeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "diftreeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            covariates = NULL,
            purification = FALSE,
            pruneNegligible = FALSE,
            alpha = 0.05,
            pAdj = "none",
            showSE = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="diftree",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..purification <- jmvcore::OptionBool$new(
                "purification",
                purification,
                default=FALSE)
            private$..pruneNegligible <- jmvcore::OptionBool$new(
                "pruneNegligible",
                pruneNegligible,
                default=FALSE)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05,
                min=0.001,
                max=0.5)
            private$..pAdj <- jmvcore::OptionList$new(
                "pAdj",
                pAdj,
                options=list(
                    "none",
                    "fdr",
                    "bonferroni"),
                default="none")
            private$..showSE <- jmvcore::OptionBool$new(
                "showSE",
                showSE,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..covariates)
            self$.addOption(private$..purification)
            self$.addOption(private$..pruneNegligible)
            self$.addOption(private$..alpha)
            self$.addOption(private$..pAdj)
            self$.addOption(private$..showSE)
        }),
    active = list(
        vars = function() private$..vars$value,
        covariates = function() private$..covariates$value,
        purification = function() private$..purification$value,
        pruneNegligible = function() private$..pruneNegligible$value,
        alpha = function() private$..alpha$value,
        pAdj = function() private$..pAdj$value,
        showSE = function() private$..showSE$value),
    private = list(
        ..vars = NA,
        ..covariates = NA,
        ..purification = NA,
        ..pruneNegligible = NA,
        ..alpha = NA,
        ..pAdj = NA,
        ..showSE = NA)
)

diftreeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "diftreeResults",
    inherit = jmvcore::Group,
    active = list(
        treePlot = function() private$.items[["treePlot"]],
        difTable = function() private$.items[["difTable"]],
        difNote = function() private$.items[["difNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Tree-Based DIF")
            self$add(jmvcore::Image$new(
                options=options,
                name="treePlot",
                title="DIF Tree",
                width=700,
                height=500,
                renderFun=".treePlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "covariates",
                    "purification",
                    "pruneNegligible",
                    "alpha",
                    "pAdj")))
            self$add(jmvcore::Table$new(
                options=options,
                name="difTable",
                title="Effect Sizes per Split",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "strobl2015",
                    "henninger2023",
                    "henninger2025",
                    "bjorner1998",
                    "zeileis2026"),
                clearWith=list(
                    "vars",
                    "covariates",
                    "purification",
                    "pruneNegligible",
                    "alpha",
                    "pAdj"),
                columns=list(
                    list(
                        `name`="node", 
                        `title`="Node", 
                        `type`="integer"),
                    list(
                        `name`="split", 
                        `title`="Split", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="effectSize", 
                        `title`="Effect size", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="class", 
                        `title`="Class", 
                        `type`="text"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text"),
                    list(
                        `name`="nLeft", 
                        `title`="Left", 
                        `type`="integer", 
                        `superTitle`="n"),
                    list(
                        `name`="nRight", 
                        `title`="Right", 
                        `type`="integer", 
                        `superTitle`="n"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="difNote",
                title="",
                clearWith=list(
                    "vars",
                    "covariates",
                    "purification",
                    "pruneNegligible",
                    "alpha",
                    "pAdj")))}))

diftreeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "diftreeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "diftree",
                version = c(1,0,0),
                options = options,
                results = diftreeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Tree-Based DIF
#'
#' Tree-based Differential Item Functioning (DIF) analysis via the
#' easyRasch2 R package (RMdifTree(), building on
#' psychotree::raschtree() / pctree()): the sample is recursively
#' split on one or more covariates wherever the item parameters are
#' unstable, so DIF is detected without pre-specifying groups.
#' Unlike the other DIF analyses in this module, several covariates
#' can be examined at once, continuous covariates (e.g. age) are
#' handled natively (the algorithm finds the optimal cutpoint), and
#' interactions emerge as nested splits.
#' 
#' For every split, each item receives an effect-size measure --
#' the Mantel-Haenszel odds ratio on the ETS Delta scale for
#' dichotomous data, or the partial gamma coefficient for
#' polytomous data -- classified into the ETS categories A
#' (negligible), B (moderate), and C (large). Optional iterative
#' purification recomputes the effect sizes while excluding
#' already-flagged items from the matching score.
#' 
#' Note that the A/B/C boundaries are conventions from large-scale
#' educational testing, not values calibrated to the sample and
#' items at hand (in contrast to the simulation-based cutoffs used
#' elsewhere in this module), so the classification is best read as
#' a rough magnitude guide. For a sample-calibrated partial-gamma
#' DIF test with a pre-specified grouping, use the Partial Gamma
#' DIF analysis with simulation-based cutoffs.
#' 
#' The analysis is deterministic (no simulation). Results are
#' identical to easyRasch2::RMdifTree().
#' 
#' @param data .
#' @param vars .
#' @param covariates .
#' @param purification .
#' @param pruneNegligible .
#' @param alpha .
#' @param pAdj .
#' @param showSE .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$treePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$difTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$difNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$difTable$asDF}
#'
#' \code{as.data.frame(results$difTable)}
#'
#' @export
diftree <- function(
    data,
    vars,
    covariates,
    purification = FALSE,
    pruneNegligible = FALSE,
    alpha = 0.05,
    pAdj = "none",
    showSE = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("diftree requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- diftreeOptions$new(
        vars = vars,
        covariates = covariates,
        purification = purification,
        pruneNegligible = pruneNegligible,
        alpha = alpha,
        pAdj = pAdj,
        showSE = showSE)

    analysis <- diftreeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

