
# This file is automatically generated, you probably don't want to edit this

iccplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iccplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            thetaMin = -5,
            thetaMax = 5, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="iccplot",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..thetaMin <- jmvcore::OptionNumber$new(
                "thetaMin",
                thetaMin,
                default=-5,
                min=-10,
                max=0)
            private$..thetaMax <- jmvcore::OptionNumber$new(
                "thetaMax",
                thetaMax,
                default=5,
                min=0,
                max=10)

            self$.addOption(private$..vars)
            self$.addOption(private$..thetaMin)
            self$.addOption(private$..thetaMax)
        }),
    active = list(
        vars = function() private$..vars$value,
        thetaMin = function() private$..thetaMin$value,
        thetaMax = function() private$..thetaMax$value),
    private = list(
        ..vars = NA,
        ..thetaMin = NA,
        ..thetaMax = NA)
)

iccplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iccplotResults",
    inherit = jmvcore::Group,
    active = list(
        iccPlot = function() private$.items[["iccPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Item Probability Curves")
            self$add(jmvcore::Image$new(
                options=options,
                name="iccPlot",
                title="Item Probability Curves",
                width=700,
                height=600,
                renderFun=".iccPlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "thetaMin",
                    "thetaMax")))}))

iccplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iccplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "iccplot",
                version = c(1,0,0),
                options = options,
                results = iccplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Item Probability Curves
#'
#' Fits a Rasch model via mirt and displays item trace (probability) curves.
#'
#' @param data .
#' @param vars .
#' @param thetaMin .
#' @param thetaMax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$iccPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
iccplot <- function(
    data,
    vars,
    thetaMin = -5,
    thetaMax = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("iccplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- iccplotOptions$new(
        vars = vars,
        thetaMin = thetaMin,
        thetaMax = thetaMax)

    analysis <- iccplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
