# This file is automatically generated, you probably don't want to edit this

itemrestscoreBase <- R6::R6Class(
    "itemrestscoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data = NULL, datasetId = "", analysisId = "", revision = 0) {
            super$initialize(
                package = 'easyRasch2jmv',
                name = 'itemrestscore',
                version = c(1, 0, 0),
                options = options,
                results = jmvcore::Group$new(
                    options = options,
                    name = "results",
                    items = list(
                        jmvcore::Table$new(
                            options = options,
                            name = "restscoreTable",
                            title = "Item-Restscore Correlations",
                            rows = "(vars)",
                            columns = list(
                                jmvcore::Column$new(
                                    name = "item",
                                    title = "Item",
                                    type = "text"
                                ),
                                jmvcore::Column$new(
                                    name = "observed",
                                    title = "Observed value",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "expected",
                                    title = "Expected value",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "absDiff",
                                    title = "Abs. difference",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "pAdjusted",
                                    title = "Adj. p-value",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "significance",
                                    title = "p-value sign.",
                                    type = "text"
                                ),
                                jmvcore::Column$new(
                                    name = "location",
                                    title = "Location",
                                    type = "number"
                                ),
                                jmvcore::Column$new(
                                    name = "relLocation",
                                    title = "Rel. location",
                                    type = "number"
                                )
                            )
                        )
                    )
                ),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision
            )
        })
)
