
# This file is automatically generated, you probably don't want to edit this

itemrestscoreOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            sortByDiff = FALSE,
            pAdj = "BH", ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="itemrestscore",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..sortByDiff <- jmvcore::OptionBool$new(
                "sortByDiff",
                sortByDiff,
                default=FALSE)
            private$..pAdj <- jmvcore::OptionList$new(
                "pAdj",
                pAdj,
                options=list(
                    "BH",
                    "holm",
                    "bonferroni"),
                default="BH")

            self$.addOption(private$..vars)
            self$.addOption(private$..sortByDiff)
            self$.addOption(private$..pAdj)
        }),
    active = list(
        vars = function() private$..vars$value,
        sortByDiff = function() private$..sortByDiff$value,
        pAdj = function() private$..pAdj$value),
    private = list(
        ..vars = NA,
        ..sortByDiff = NA,
        ..pAdj = NA)
)

itemrestscoreResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreResults",
    inherit = jmvcore::Group,
    active = list(
        restscoreTable = function() private$.items[["restscoreTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Item-Restscore Correlations")
            self$add(jmvcore::Table$new(
                options=options,
                name="restscoreTable",
                title="Item-Restscore Correlations",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "sortByDiff",
                    "pAdj"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="observed", 
                        `title`="Observed value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="expected", 
                        `title`="Expected value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="absDiff", 
                        `title`="Abs. difference", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pAdjusted", 
                        `title`="Adj. p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="significance", 
                        `title`="p-value sign.", 
                        `type`="text"),
                    list(
                        `name`="location", 
                        `title`="Location", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

itemrestscoreBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "itemrestscore",
                version = c(1,0,0),
                options = options,
                results = itemrestscoreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Item-Restscore Correlations
#'
#' Computes observed and model-expected item-restscore correlations using
#' Goodman-Kruskal's gamma (via the iarm package). Fits a Rasch model
#' (dichotomous data) or Partial Credit Model (polytomous data) using eRm,
#' then reports observed vs. expected restscore correlations, absolute
#' differences, adjusted p-values, and item locations.
#' 
#' @param data .
#' @param vars .
#' @param sortByDiff .
#' @param pAdj .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restscoreTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restscoreTable$asDF}
#'
#' \code{as.data.frame(results$restscoreTable)}
#'
#' @export
itemrestscore <- function(
    data,
    vars,
    sortByDiff = FALSE,
    pAdj = "BH") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("itemrestscore requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- itemrestscoreOptions$new(
        vars = vars,
        sortByDiff = sortByDiff,
        pAdj = pAdj)

    analysis <- itemrestscoreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

