
# This file is automatically generated, you probably don't want to edit this

iteminfitmiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitmiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            auxVars = NULL,
            method = "polr",
            m = 5,
            maxit = 15,
            seed = 42,
            sortByInfit = FALSE,
            computeCutoff = FALSE,
            hdciWidth = 99.9,
            iterations = 500, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="iteminfitmi",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..auxVars <- jmvcore::OptionVariables$new(
                "auxVars",
                auxVars,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "polr",
                    "pmm",
                    "cart"),
                default="polr")
            private$..m <- jmvcore::OptionInteger$new(
                "m",
                m,
                default=5,
                min=2,
                max=50)
            private$..maxit <- jmvcore::OptionInteger$new(
                "maxit",
                maxit,
                default=15,
                min=5,
                max=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..sortByInfit <- jmvcore::OptionBool$new(
                "sortByInfit",
                sortByInfit,
                default=FALSE)
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..hdciWidth <- jmvcore::OptionNumber$new(
                "hdciWidth",
                hdciWidth,
                default=99.9,
                min=50,
                max=100)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=500,
                min=50)

            self$.addOption(private$..vars)
            self$.addOption(private$..auxVars)
            self$.addOption(private$..method)
            self$.addOption(private$..m)
            self$.addOption(private$..maxit)
            self$.addOption(private$..seed)
            self$.addOption(private$..sortByInfit)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..hdciWidth)
            self$.addOption(private$..iterations)
        }),
    active = list(
        vars = function() private$..vars$value,
        auxVars = function() private$..auxVars$value,
        method = function() private$..method$value,
        m = function() private$..m$value,
        maxit = function() private$..maxit$value,
        seed = function() private$..seed$value,
        sortByInfit = function() private$..sortByInfit$value,
        computeCutoff = function() private$..computeCutoff$value,
        hdciWidth = function() private$..hdciWidth$value,
        iterations = function() private$..iterations$value),
    private = list(
        ..vars = NA,
        ..auxVars = NA,
        ..method = NA,
        ..m = NA,
        ..maxit = NA,
        ..seed = NA,
        ..sortByInfit = NA,
        ..computeCutoff = NA,
        ..hdciWidth = NA,
        ..iterations = NA)
)

iteminfitmiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitmiResults",
    inherit = jmvcore::Group,
    active = list(
        infitTable = function() private$.items[["infitTable"]],
        imputationNote = function() private$.items[["imputationNote"]],
        infitPlot = function() private$.items[["infitPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Conditional Item Infit (Multiple Imputation)")
            self$add(jmvcore::Table$new(
                options=options,
                name="infitTable",
                title="Pooled Conditional Item Infit MSQ",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "mueller2020",
                    "johansson2025_detecting",
                    "mair2007",
                    "mueller2022",
                    "vanbuuren2011",
                    "kay2025"),
                clearWith=list(
                    "vars",
                    "auxVars",
                    "method",
                    "m",
                    "maxit",
                    "seed",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="infitMSQ", 
                        `title`="Infit MSQ", 
                        `type`="number"),
                    list(
                        `name`="infitSE", 
                        `title`="Pooled SE", 
                        `type`="number"),
                    list(
                        `name`="infitLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="infitHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="imputationNote",
                title="",
                clearWith=list(
                    "vars",
                    "auxVars",
                    "method",
                    "m",
                    "maxit",
                    "seed",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations")))
            self$add(jmvcore::Image$new(
                options=options,
                name="infitPlot",
                title="Simulated Infit MSQ Distribution",
                width=400,
                height=500,
                renderFun=".infitPlot",
                visible="(computeCutoff)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "auxVars",
                    "method",
                    "m",
                    "maxit",
                    "seed",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations")))}))

iteminfitmiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitmiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "iteminfitmi",
                version = c(1,0,0),
                options = options,
                results = iteminfitmiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Conditional Item Infit (Multiple Imputation)
#'
#' Computes pooled conditional infit MSQ statistics for items with missing
#' responses. Internally runs mice::mice() to generate \code{m} imputed 
#' datasets,
#' fits a Rasch model (eRm::RM for dichotomous, eRm::PCM for polytomous) on
#' each, computes conditional infit MSQ via iarm::out_infit(), and pools
#' per-item estimates and standard errors using Rubin's rules.
#' 
#' Imputation method defaults to 'polr' (proportional-odds logistic
#' regression — appropriate for ordinal Likert data). 'pmm' (predictive
#' mean matching) and 'cart' (classification and regression trees) are
#' available as alternatives if 'polr' fails to converge. Auxiliary
#' variables (covariates not part of the scale) can be added as predictors
#' in the imputation model to improve plausibility of the MAR assumption.
#' 
#' Optionally computes simulation-based per-item cutoffs by running a
#' parametric bootstrap on each imputed dataset and stacking the
#' distributions, so the resulting HDCI bounds reflect both sampling and
#' imputation uncertainty.
#' 
#' @param data .
#' @param vars .
#' @param auxVars .
#' @param method .
#' @param m .
#' @param maxit .
#' @param seed .
#' @param sortByInfit .
#' @param computeCutoff .
#' @param hdciWidth .
#' @param iterations .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$infitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$imputationNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infitPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infitTable$asDF}
#'
#' \code{as.data.frame(results$infitTable)}
#'
#' @export
iteminfitmi <- function(
    data,
    vars,
    auxVars = NULL,
    method = "polr",
    m = 5,
    maxit = 15,
    seed = 42,
    sortByInfit = FALSE,
    computeCutoff = FALSE,
    hdciWidth = 99.9,
    iterations = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("iteminfitmi requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(auxVars)) auxVars <- jmvcore::resolveQuo(jmvcore::enquo(auxVars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(auxVars), auxVars, NULL))


    options <- iteminfitmiOptions$new(
        vars = vars,
        auxVars = auxVars,
        method = method,
        m = m,
        maxit = maxit,
        seed = seed,
        sortByInfit = sortByInfit,
        computeCutoff = computeCutoff,
        hdciWidth = hdciWidth,
        iterations = iterations)

    analysis <- iteminfitmiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

