
# This file is automatically generated, you probably don't want to edit this

iteminfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            computeCutoff = FALSE,
            hdciWidth = 95,
            iterations = 400,
            seed = 42,
            pValues = TRUE,
            correction = "fwer",
            sortByInfit = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="iteminfit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..hdciWidth <- jmvcore::OptionNumber$new(
                "hdciWidth",
                hdciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=400,
                min=50)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..pValues <- jmvcore::OptionBool$new(
                "pValues",
                pValues,
                default=TRUE)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "fwer",
                    "fdr_bh",
                    "fdr_by"),
                default="fwer")
            private$..sortByInfit <- jmvcore::OptionBool$new(
                "sortByInfit",
                sortByInfit,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..hdciWidth)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
            self$.addOption(private$..pValues)
            self$.addOption(private$..correction)
            self$.addOption(private$..sortByInfit)
        }),
    active = list(
        vars = function() private$..vars$value,
        computeCutoff = function() private$..computeCutoff$value,
        hdciWidth = function() private$..hdciWidth$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value,
        pValues = function() private$..pValues$value,
        correction = function() private$..correction$value,
        sortByInfit = function() private$..sortByInfit$value),
    private = list(
        ..vars = NA,
        ..computeCutoff = NA,
        ..hdciWidth = NA,
        ..iterations = NA,
        ..seed = NA,
        ..pValues = NA,
        ..correction = NA,
        ..sortByInfit = NA)
)

iteminfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitResults",
    inherit = jmvcore::Group,
    active = list(
        infitTable = function() private$.items[["infitTable"]],
        cutoffNote = function() private$.items[["cutoffNote"]],
        infitPlot = function() private$.items[["infitPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Conditional Item Infit")
            self$add(jmvcore::Table$new(
                options=options,
                name="infitTable",
                title="Conditional Item Infit MSQ",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "mueller2020",
                    "johansson2025_detecting",
                    "johansson2026_cutoffs",
                    "mueller2022",
                    "zeileis2026",
                    "warm1989",
                    "kay2025",
                    "ferreira2024",
                    "westfallyoung1993"),
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed",
                    "pValues",
                    "correction",
                    "sortByInfit"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="infitMSQ", 
                        `title`="Observed infit", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="infitLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="infitHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="pValue", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="pAdjusted", 
                        `title`="Adj. p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="misfit", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="cutoffNote",
                title="",
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed",
                    "pValues",
                    "correction")))
            self$add(jmvcore::Image$new(
                options=options,
                name="infitPlot",
                title="Simulated Infit MSQ Distribution",
                width=500,
                height=600,
                renderFun=".infitPlot",
                visible="(computeCutoff)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed")))}))

iteminfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "iteminfit",
                version = c(1,0,0),
                options = options,
                results = iteminfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Conditional Item Infit
#'
#' Computes conditional infit MSQ statistics for each item using the
#' easyRasch2 R package (iarm::out_infit() on a conditional maximum
#' likelihood fit via psychotools, with WLE person estimates for the
#' relative item locations). Optionally determines simulation-based
#' per-item cutoff intervals via parametric bootstrap: datasets are
#' simulated under the fitted model (no misfit by construction) and
#' the HDCI of each item's simulated infit forms the expected range.
#' Items are labelled overfit (infit below the range; more predictable
#' than the model expects) or underfit (above; noisier than expected).
#' Results match easyRasch2::RMitemInfit(), RMitemInfitCutoff(), and
#' RMitemInfitPlot() with the same seed and iterations. Single-core
#' sequential processing is used.
#' 
#' Note on iterations: 400 is a calibrated floor and 1000 to 2000 is
#' advisable for a final analysis (Johansson, 2026). Below 400 the
#' multiple-comparison correction is mildly liberal, and while error
#' rates are calibrated from 400 onward, decisions remain somewhat
#' seed-dependent until well past it. An earlier recommendation that
#' around 100 iterations could give better detection with small
#' samples is withdrawn: that advantage came from an expected range
#' that had not converged, and was paid for with an inflated
#' familywise error rate.
#' 
#' Bootstrap p-values are computed by default: each item's observed
#' infit is compared against its simulated distribution (Monte-Carlo
#' p-value), with correction for multiple comparisons across items --
#' Westfall-Young step-down (familywise error rate, the default;
#' Ferreira, 2024), Benjamini-Hochberg, or Benjamini-Yekutieli (false
#' discovery rate). Flagging is based on the adjusted p-value
#' (< 0.05). Turning them off flags against the expected range
#' instead, which applies one interval to every item at once and so
#' implies a familywise error rate of 1 - width^k over k items, 37\%
#' for a 95\% range over nine items. The range is best read as a
#' description of where a fitting item's infit is expected to fall.
#' Results match easyRasch2::RMitemInfit().
#' 
#' @param data .
#' @param vars .
#' @param computeCutoff .
#' @param hdciWidth .
#' @param iterations .
#' @param seed .
#' @param pValues .
#' @param correction .
#' @param sortByInfit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$infitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cutoffNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infitPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infitTable$asDF}
#'
#' \code{as.data.frame(results$infitTable)}
#'
#' @export
iteminfit <- function(
    data,
    vars,
    computeCutoff = FALSE,
    hdciWidth = 95,
    iterations = 400,
    seed = 42,
    pValues = TRUE,
    correction = "fwer",
    sortByInfit = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("iteminfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- iteminfitOptions$new(
        vars = vars,
        computeCutoff = computeCutoff,
        hdciWidth = hdciWidth,
        iterations = iterations,
        seed = seed,
        pValues = pValues,
        correction = correction,
        sortByInfit = sortByInfit)

    analysis <- iteminfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

