
# This file is automatically generated, you probably don't want to edit this

iteminfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            computeCutoff = FALSE,
            hdciWidth = 99,
            iterations = 200,
            seed = 42,
            sortByInfit = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="iteminfit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..hdciWidth <- jmvcore::OptionNumber$new(
                "hdciWidth",
                hdciWidth,
                default=99,
                min=50,
                max=100)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=200,
                min=50)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..sortByInfit <- jmvcore::OptionBool$new(
                "sortByInfit",
                sortByInfit,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..hdciWidth)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
            self$.addOption(private$..sortByInfit)
        }),
    active = list(
        vars = function() private$..vars$value,
        computeCutoff = function() private$..computeCutoff$value,
        hdciWidth = function() private$..hdciWidth$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value,
        sortByInfit = function() private$..sortByInfit$value),
    private = list(
        ..vars = NA,
        ..computeCutoff = NA,
        ..hdciWidth = NA,
        ..iterations = NA,
        ..seed = NA,
        ..sortByInfit = NA)
)

iteminfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitResults",
    inherit = jmvcore::Group,
    active = list(
        infitTable = function() private$.items[["infitTable"]],
        cutoffNote = function() private$.items[["cutoffNote"]],
        infitPlot = function() private$.items[["infitPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Conditional Item Infit")
            self$add(jmvcore::Table$new(
                options=options,
                name="infitTable",
                title="Conditional Item Infit MSQ",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "mueller2020",
                    "johansson2025_detecting",
                    "mair2007",
                    "zeileis2026",
                    "kay2025"),
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed",
                    "sortByInfit"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="infitMSQ", 
                        `title`="Observed infit", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="infitLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="infitHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="misfit", 
                        `title`="Misfit", 
                        `type`="text", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="cutoffNote",
                title="",
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="infitPlot",
                title="Simulated Infit MSQ Distribution",
                width=500,
                height=600,
                renderFun=".infitPlot",
                visible="(computeCutoff)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed")))}))

iteminfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "iteminfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "iteminfit",
                version = c(1,0,0),
                options = options,
                results = iteminfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Conditional Item Infit
#'
#' Computes conditional infit MSQ statistics for each item using
#' iarm::out_infit() (CML item parameters from eRm; RM for dichotomous
#' data, PCM for polytomous -- chosen automatically). Optionally
#' determines simulation-based per-item cutoff intervals via parametric
#' bootstrap: datasets are simulated under the fitted model (no misfit
#' by construction) and the HDCI of each item's simulated infit forms
#' the expected range. Items are labelled overfit (infit below the
#' range; more predictable than the model expects) or underfit (above;
#' noisier than expected).
#' 
#' Note on iterations: more simulation iterations are generally
#' recommended for publication-ready results. Conditional infit is an
#' exception: with small samples, around 100 iterations can yield
#' better detection power than a larger number (Johansson, 2025).
#' 
#' @param data .
#' @param vars .
#' @param computeCutoff .
#' @param hdciWidth .
#' @param iterations .
#' @param seed .
#' @param sortByInfit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$infitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cutoffNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infitPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$infitTable$asDF}
#'
#' \code{as.data.frame(results$infitTable)}
#'
#' @export
iteminfit <- function(
    data,
    vars,
    computeCutoff = FALSE,
    hdciWidth = 99,
    iterations = 200,
    seed = 42,
    sortByInfit = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("iteminfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- iteminfitOptions$new(
        vars = vars,
        computeCutoff = computeCutoff,
        hdciWidth = hdciWidth,
        iterations = iterations,
        seed = seed,
        sortByInfit = sortByInfit)

    analysis <- iteminfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

