
# This file is automatically generated, you probably don't want to edit this

itemrestscoreOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            sortByDiff = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="itemrestscore",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..sortByDiff <- jmvcore::OptionBool$new(
                "sortByDiff",
                sortByDiff,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..sortByDiff)
        }),
    active = list(
        vars = function() private$..vars$value,
        sortByDiff = function() private$..sortByDiff$value),
    private = list(
        ..vars = NA,
        ..sortByDiff = NA)
)

itemrestscoreResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreResults",
    inherit = jmvcore::Group,
    active = list(
        restscoreTable = function() private$.items[["restscoreTable"]],
        restscoreNote = function() private$.items[["restscoreNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Item-Restscore Correlations")
            self$add(jmvcore::Table$new(
                options=options,
                name="restscoreTable",
                title="Item-Restscore Correlations",
                rows="(vars)",
                refs=list(
                    "easyRasch2jmv",
                    "kreiner2011",
                    "mueller2022",
                    "mair2007"),
                clearWith=list(
                    "vars",
                    "sortByDiff"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="observed", 
                        `title`="Observed gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="expected", 
                        `title`="Expected gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="difference", 
                        `title`="Difference", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pAdjusted", 
                        `title`="Adj. p-value (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="fit", 
                        `title`="Flagged", 
                        `type`="text"),
                    list(
                        `name`="relLocation", 
                        `title`="Rel. location", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="restscoreNote",
                title="",
                clearWith=list(
                    "vars")))}))

itemrestscoreBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemrestscoreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "itemrestscore",
                version = c(1,0,0),
                options = options,
                results = itemrestscoreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Item-Restscore Correlations
#'
#' Computes observed and model-expected item-restscore correlations using
#' Goodman-Kruskal's gamma (via the iarm package). Fits a Rasch model
#' (dichotomous data) or Partial Credit Model (polytomous data) using eRm,
#' then reports observed vs. expected restscore correlations, the signed
#' difference (observed minus expected; positive = over-discrimination /
#' often LD, negative = under-discrimination / often noise),
#' adjusted p-values, and item locations.
#' 
#' @param data .
#' @param vars .
#' @param sortByDiff .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$restscoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$restscoreNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$restscoreTable$asDF}
#'
#' \code{as.data.frame(results$restscoreTable)}
#'
#' @export
itemrestscore <- function(
    data,
    vars,
    sortByDiff = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("itemrestscore requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- itemrestscoreOptions$new(
        vars = vars,
        sortByDiff = sortByDiff)

    analysis <- itemrestscoreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

