
# This file is automatically generated, you probably don't want to edit this

locdepq3Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepq3Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            computeCutoff = FALSE,
            iterations = 100,
            seed = 42, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="locdepq3",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=100,
                min=50,
                max=5000)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42,
                min=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
        }),
    active = list(
        vars = function() private$..vars$value,
        computeCutoff = function() private$..computeCutoff$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value),
    private = list(
        ..vars = NA,
        ..computeCutoff = NA,
        ..iterations = NA,
        ..seed = NA)
)

locdepq3Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepq3Results",
    inherit = jmvcore::Group,
    active = list(
        q3Table = function() private$.items[["q3Table"]],
        cutoffTable = function() private$.items[["cutoffTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Q3 Residual Correlation Matrix")
            self$add(jmvcore::Table$new(
                options=options,
                name="q3Table",
                title="Q3 Residual Correlation Matrix",
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "iterations",
                    "seed"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="cutoffTable",
                title="Simulation-Based Q3 Cutoff",
                visible="(computeCutoff)",
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "iterations",
                    "seed"),
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"))))}))

locdepq3Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepq3Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "locdepq3",
                version = c(1,0,0),
                options = options,
                results = locdepq3Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Q3 Residual Correlation Matrix
#'
#' Computes Yen's Q3 residual correlations between item pairs for local
#' dependence assessment in Rasch models (fitted via mirt). Optionally
#' runs a parametric bootstrap simulation to determine a simulation-based
#' cutoff value. Single-core sequential processing is used by default.
#' 
#' @param data .
#' @param vars .
#' @param computeCutoff .
#' @param iterations .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$q3Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cutoffTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$q3Table$asDF}
#'
#' \code{as.data.frame(results$q3Table)}
#'
#' @export
locdepq3 <- function(
    data,
    vars,
    computeCutoff = FALSE,
    iterations = 100,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("locdepq3 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- locdepq3Options$new(
        vars = vars,
        computeCutoff = computeCutoff,
        iterations = iterations,
        seed = seed)

    analysis <- locdepq3Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

