
# This file is automatically generated, you probably don't want to edit this

locdepgammaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nPairs = 0,
            sigOnly = FALSE,
            gammaThreshold = 0,
            sortByGamma = FALSE,
            showSE = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="locdepgamma",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..nPairs <- jmvcore::OptionInteger$new(
                "nPairs",
                nPairs,
                default=0,
                min=0)
            private$..sigOnly <- jmvcore::OptionBool$new(
                "sigOnly",
                sigOnly,
                default=FALSE)
            private$..gammaThreshold <- jmvcore::OptionNumber$new(
                "gammaThreshold",
                gammaThreshold,
                default=0,
                min=0,
                max=1)
            private$..sortByGamma <- jmvcore::OptionBool$new(
                "sortByGamma",
                sortByGamma,
                default=FALSE)
            private$..showSE <- jmvcore::OptionBool$new(
                "showSE",
                showSE,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..nPairs)
            self$.addOption(private$..sigOnly)
            self$.addOption(private$..gammaThreshold)
            self$.addOption(private$..sortByGamma)
            self$.addOption(private$..showSE)
        }),
    active = list(
        vars = function() private$..vars$value,
        nPairs = function() private$..nPairs$value,
        sigOnly = function() private$..sigOnly$value,
        gammaThreshold = function() private$..gammaThreshold$value,
        sortByGamma = function() private$..sortByGamma$value,
        showSE = function() private$..showSE$value),
    private = list(
        ..vars = NA,
        ..nPairs = NA,
        ..sigOnly = NA,
        ..gammaThreshold = NA,
        ..sortByGamma = NA,
        ..showSE = NA)
)

locdepgammaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaResults",
    inherit = jmvcore::Group,
    active = list(
        dir1Table = function() private$.items[["dir1Table"]],
        dir2Table = function() private$.items[["dir2Table"]],
        ldNote = function() private$.items[["ldNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Gamma Local Dependence")
            self$add(jmvcore::Table$new(
                options=options,
                name="dir1Table",
                title="Direction 1: Rest Score = Total \u2212 Item 2",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "christensen2013",
                    "mueller2022"),
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma"),
                columns=list(
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="gamma", 
                        `title`="Partial gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="padjBH", 
                        `title`="Adj. p-value (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="sig", 
                        `title`="p-value sign.", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dir2Table",
                title="Direction 2: Rest Score = Total \u2212 Item 1",
                rows=0,
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma"),
                columns=list(
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="gamma", 
                        `title`="Partial gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="padjBH", 
                        `title`="Adj. p-value (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="sig", 
                        `title`="p-value sign.", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="ldNote",
                title="",
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma",
                    "showSE")))}))

locdepgammaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "locdepgamma",
                version = c(1,0,0),
                options = options,
                results = locdepgammaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Partial Gamma Local Dependence
#'
#' 
#' @param data .
#' @param vars .
#' @param nPairs .
#' @param sigOnly .
#' @param gammaThreshold .
#' @param sortByGamma .
#' @param showSE .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dir1Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dir2Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ldNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dir1Table$asDF}
#'
#' \code{as.data.frame(results$dir1Table)}
#'
#' @export
locdepgamma <- function(
    data,
    vars,
    nPairs = 0,
    sigOnly = FALSE,
    gammaThreshold = 0,
    sortByGamma = FALSE,
    showSE = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("locdepgamma requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- locdepgammaOptions$new(
        vars = vars,
        nPairs = nPairs,
        sigOnly = sigOnly,
        gammaThreshold = gammaThreshold,
        sortByGamma = sortByGamma,
        showSE = showSE)

    analysis <- locdepgammaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

