
# This file is automatically generated, you probably don't want to edit this

locdepgammaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nPairs = 0,
            sigOnly = FALSE,
            gammaThreshold = 0,
            sortByGamma = FALSE,
            computeCutoff = FALSE,
            iterations = 400,
            hdciWidth = 95,
            seed = 42,
            pValues = TRUE,
            correction = "fwer",
            plotPairs = 10,
            showSE = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="locdepgamma",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..nPairs <- jmvcore::OptionInteger$new(
                "nPairs",
                nPairs,
                default=0,
                min=0)
            private$..sigOnly <- jmvcore::OptionBool$new(
                "sigOnly",
                sigOnly,
                default=FALSE)
            private$..gammaThreshold <- jmvcore::OptionNumber$new(
                "gammaThreshold",
                gammaThreshold,
                default=0,
                min=0,
                max=1)
            private$..sortByGamma <- jmvcore::OptionBool$new(
                "sortByGamma",
                sortByGamma,
                default=FALSE)
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=400,
                min=50,
                max=5000)
            private$..hdciWidth <- jmvcore::OptionNumber$new(
                "hdciWidth",
                hdciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42,
                min=0)
            private$..pValues <- jmvcore::OptionBool$new(
                "pValues",
                pValues,
                default=TRUE)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "fwer",
                    "fdr_bh",
                    "fdr_by"),
                default="fwer")
            private$..plotPairs <- jmvcore::OptionInteger$new(
                "plotPairs",
                plotPairs,
                default=10,
                min=1,
                max=50)
            private$..showSE <- jmvcore::OptionBool$new(
                "showSE",
                showSE,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..nPairs)
            self$.addOption(private$..sigOnly)
            self$.addOption(private$..gammaThreshold)
            self$.addOption(private$..sortByGamma)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..iterations)
            self$.addOption(private$..hdciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..pValues)
            self$.addOption(private$..correction)
            self$.addOption(private$..plotPairs)
            self$.addOption(private$..showSE)
        }),
    active = list(
        vars = function() private$..vars$value,
        nPairs = function() private$..nPairs$value,
        sigOnly = function() private$..sigOnly$value,
        gammaThreshold = function() private$..gammaThreshold$value,
        sortByGamma = function() private$..sortByGamma$value,
        computeCutoff = function() private$..computeCutoff$value,
        iterations = function() private$..iterations$value,
        hdciWidth = function() private$..hdciWidth$value,
        seed = function() private$..seed$value,
        pValues = function() private$..pValues$value,
        correction = function() private$..correction$value,
        plotPairs = function() private$..plotPairs$value,
        showSE = function() private$..showSE$value),
    private = list(
        ..vars = NA,
        ..nPairs = NA,
        ..sigOnly = NA,
        ..gammaThreshold = NA,
        ..sortByGamma = NA,
        ..computeCutoff = NA,
        ..iterations = NA,
        ..hdciWidth = NA,
        ..seed = NA,
        ..pValues = NA,
        ..correction = NA,
        ..plotPairs = NA,
        ..showSE = NA)
)

locdepgammaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaResults",
    inherit = jmvcore::Group,
    active = list(
        dir1Table = function() private$.items[["dir1Table"]],
        dir2Table = function() private$.items[["dir2Table"]],
        ldPlot = function() private$.items[["ldPlot"]],
        simCache = function() private$.items[["simCache"]],
        ldNote = function() private$.items[["ldNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Gamma Local Dependence")
            self$add(jmvcore::Table$new(
                options=options,
                name="dir1Table",
                title="Direction 1: rest score = total \u2212 Item 2",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "christensen2013",
                    "johansson2026_cutoffs",
                    "mueller2022",
                    "kay2025",
                    "ferreira2024",
                    "westfallyoung1993"),
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma",
                    "computeCutoff",
                    "iterations",
                    "hdciWidth",
                    "seed",
                    "pValues",
                    "correction"),
                columns=list(
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="gamma", 
                        `title`="Partial gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="gammaPair", 
                        `title`="Gamma pair", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="padjBH", 
                        `title`="Adj. p-value (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(!(computeCutoff && pValues))"),
                    list(
                        `name`="sig", 
                        `title`="p-value sign.", 
                        `type`="text", 
                        `visible`="(!(computeCutoff && pValues))"),
                    list(
                        `name`="gammaLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="gammaHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="pValue", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="pAdjusted", 
                        `title`="Adj. p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dir2Table",
                title="Direction 2: rest score = total \u2212 Item 2",
                rows=0,
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma",
                    "computeCutoff",
                    "iterations",
                    "hdciWidth",
                    "seed",
                    "pValues",
                    "correction"),
                columns=list(
                    list(
                        `name`="item1", 
                        `title`="Item 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Item 2", 
                        `type`="text"),
                    list(
                        `name`="gamma", 
                        `title`="Partial gamma", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showSE)", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="gammaPair", 
                        `title`="Gamma pair", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="padjBH", 
                        `title`="Adj. p-value (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(!(computeCutoff && pValues))"),
                    list(
                        `name`="sig", 
                        `title`="p-value sign.", 
                        `type`="text", 
                        `visible`="(!(computeCutoff && pValues))"),
                    list(
                        `name`="gammaLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="gammaHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)", 
                        `superTitle`="Expected range"),
                    list(
                        `name`="pValue", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="pAdjusted", 
                        `title`="Adj. p-value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(computeCutoff && pValues)"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="ldPlot",
                title="Simulated Partial Gamma Distribution per Item Pair",
                width=500,
                height=600,
                renderFun=".ldPlot",
                visible="(computeCutoff)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "iterations",
                    "seed",
                    "plotPairs")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "computeCutoff",
                    "iterations",
                    "hdciWidth",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="ldNote",
                title="",
                clearWith=list(
                    "vars",
                    "nPairs",
                    "sigOnly",
                    "gammaThreshold",
                    "sortByGamma",
                    "computeCutoff",
                    "iterations",
                    "hdciWidth",
                    "seed",
                    "pValues",
                    "correction",
                    "showSE")))}))

locdepgammaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "locdepgammaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "locdepgamma",
                version = c(1,0,0),
                options = options,
                results = locdepgammaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Partial Gamma Local Dependence
#'
#' Computes partial gamma coefficients for Local Dependence (LD)
#' assessment via the easyRasch2 R package (iarm::partgam_LD()). Each
#' pair of items is tested for residual association, controlling for
#' the rest score (total score minus one of the items in the pair).
#' Because it matters which item of a pair is subtracted from the
#' total score, each pair is tested in both rest-score directions
#' (two tables). Optionally determines simulation-based per-pair
#' expected ranges via parametric bootstrap (data simulated from the
#' fitted model contain no true LD), with a plot of the simulated
#' distributions and observed values. Results are identical to
#' easyRasch2::RMlocdepGamma(), RMlocdepGammaCutoff(), and
#' RMlocdepGammaPlot() with the same seed and iterations. Single-core
#' sequential processing is used.
#' 
#' @param data .
#' @param vars .
#' @param nPairs .
#' @param sigOnly .
#' @param gammaThreshold .
#' @param sortByGamma .
#' @param computeCutoff .
#' @param iterations .
#' @param hdciWidth .
#' @param seed .
#' @param pValues .
#' @param correction .
#' @param plotPairs .
#' @param showSE .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dir1Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dir2Table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ldPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simCache} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ldNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dir1Table$asDF}
#'
#' \code{as.data.frame(results$dir1Table)}
#'
#' @export
locdepgamma <- function(
    data,
    vars,
    nPairs = 0,
    sigOnly = FALSE,
    gammaThreshold = 0,
    sortByGamma = FALSE,
    computeCutoff = FALSE,
    iterations = 400,
    hdciWidth = 95,
    seed = 42,
    pValues = TRUE,
    correction = "fwer",
    plotPairs = 10,
    showSE = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("locdepgamma requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- locdepgammaOptions$new(
        vars = vars,
        nPairs = nPairs,
        sigOnly = sigOnly,
        gammaThreshold = gammaThreshold,
        sortByGamma = sortByGamma,
        computeCutoff = computeCutoff,
        iterations = iterations,
        hdciWidth = hdciWidth,
        seed = seed,
        pValues = pValues,
        correction = correction,
        plotPairs = plotPairs,
        showSE = showSE)

    analysis <- locdepgammaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

