
# This file is automatically generated, you probably don't want to edit this

lrdifOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrdifOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            difVar = NULL,
            level = "item",
            cutoff = 0.5,
            sortByMaxDiff = FALSE,
            showFigure = FALSE,
            confLevel = 95,
            showTileplot = FALSE,
            tileCutoff = 10,
            tilePercent = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="lrdif",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..difVar <- jmvcore::OptionVariable$new(
                "difVar",
                difVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..level <- jmvcore::OptionList$new(
                "level",
                level,
                options=list(
                    "item",
                    "threshold"),
                default="item")
            private$..cutoff <- jmvcore::OptionNumber$new(
                "cutoff",
                cutoff,
                default=0.5,
                min=0,
                max=5)
            private$..sortByMaxDiff <- jmvcore::OptionBool$new(
                "sortByMaxDiff",
                sortByMaxDiff,
                default=FALSE)
            private$..showFigure <- jmvcore::OptionBool$new(
                "showFigure",
                showFigure,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=95,
                min=50,
                max=99.9)
            private$..showTileplot <- jmvcore::OptionBool$new(
                "showTileplot",
                showTileplot,
                default=FALSE)
            private$..tileCutoff <- jmvcore::OptionInteger$new(
                "tileCutoff",
                tileCutoff,
                default=10,
                min=1)
            private$..tilePercent <- jmvcore::OptionBool$new(
                "tilePercent",
                tilePercent,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..difVar)
            self$.addOption(private$..level)
            self$.addOption(private$..cutoff)
            self$.addOption(private$..sortByMaxDiff)
            self$.addOption(private$..showFigure)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..showTileplot)
            self$.addOption(private$..tileCutoff)
            self$.addOption(private$..tilePercent)
        }),
    active = list(
        vars = function() private$..vars$value,
        difVar = function() private$..difVar$value,
        level = function() private$..level$value,
        cutoff = function() private$..cutoff$value,
        sortByMaxDiff = function() private$..sortByMaxDiff$value,
        showFigure = function() private$..showFigure$value,
        confLevel = function() private$..confLevel$value,
        showTileplot = function() private$..showTileplot$value,
        tileCutoff = function() private$..tileCutoff$value,
        tilePercent = function() private$..tilePercent$value),
    private = list(
        ..vars = NA,
        ..difVar = NA,
        ..level = NA,
        ..cutoff = NA,
        ..sortByMaxDiff = NA,
        ..showFigure = NA,
        ..confLevel = NA,
        ..showTileplot = NA,
        ..tileCutoff = NA,
        ..tilePercent = NA)
)

lrdifResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrdifResults",
    inherit = jmvcore::Group,
    active = list(
        lrtTable = function() private$.items[["lrtTable"]],
        lrtNote = function() private$.items[["lrtNote"]],
        lrtPlot = function() private$.items[["lrtPlot"]],
        tileplot = function() private$.items[["tileplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Andersen LR-test DIF")
            self$add(jmvcore::Table$new(
                options=options,
                name="lrtTable",
                title="Per-group Item Locations",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "mair2007"),
                clearWith=list(
                    "vars",
                    "difVar",
                    "level",
                    "cutoff",
                    "sortByMaxDiff"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="lrtNote",
                title="",
                clearWith=list(
                    "vars",
                    "difVar",
                    "level",
                    "cutoff")))
            self$add(jmvcore::Image$new(
                options=options,
                name="lrtPlot",
                title="Per-group Locations",
                width=600,
                height=600,
                renderFun=".lrtPlot",
                visible="(showFigure)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "difVar",
                    "level",
                    "confLevel")))
            self$add(jmvcore::Image$new(
                options=options,
                name="tileplot",
                title="Response Distribution by DIF Group",
                width=600,
                height=600,
                renderFun=".tileplot",
                visible="(showTileplot)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "difVar",
                    "showTileplot",
                    "tileCutoff",
                    "tilePercent")))}))

lrdifBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrdifBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "lrdif",
                version = c(1,0,0),
                options = options,
                results = lrdifResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Andersen LR-test DIF
#'
#' Splits a Rasch model by an external categorical grouping variable
#' using \code{eRm::LRtest()} (Andersen's likelihood-ratio test) and reports
#' per-group item locations (or per-group threshold locations) together
#' with their standard errors. The dichotomous Rasch Model (RM) is
#' fitted when the data are 0/1; the Partial Credit Model (PCM)
#' otherwise -- chosen automatically.
#' 
#' Items whose largest group difference (MaxDiff) exceeds the chosen
#' cutoff (in logits) are flagged. The Andersen LR test statistic is
#' reported below the table.
#' 
#' @param data .
#' @param vars .
#' @param difVar .
#' @param level .
#' @param cutoff .
#' @param sortByMaxDiff .
#' @param showFigure .
#' @param confLevel .
#' @param showTileplot .
#' @param tileCutoff .
#' @param tilePercent .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$lrtTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lrtNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$lrtPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tileplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lrtTable$asDF}
#'
#' \code{as.data.frame(results$lrtTable)}
#'
#' @export
lrdif <- function(
    data,
    vars,
    difVar,
    level = "item",
    cutoff = 0.5,
    sortByMaxDiff = FALSE,
    showFigure = FALSE,
    confLevel = 95,
    showTileplot = FALSE,
    tileCutoff = 10,
    tilePercent = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lrdif requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(difVar)) difVar <- jmvcore::resolveQuo(jmvcore::enquo(difVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(difVar), difVar, NULL))

    for (v in difVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lrdifOptions$new(
        vars = vars,
        difVar = difVar,
        level = level,
        cutoff = cutoff,
        sortByMaxDiff = sortByMaxDiff,
        showFigure = showFigure,
        confLevel = confLevel,
        showTileplot = showTileplot,
        tileCutoff = tileCutoff,
        tilePercent = tilePercent)

    analysis <- lrdifClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

