
# This file is automatically generated, you probably don't want to edit this

martinlofOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "martinlofOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            subscale1 = NULL,
            subscale2 = NULL,
            iterations = 250,
            seed = 42,
            sequential = FALSE,
            minExpected = 0, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="martinlof",
                requiresData=TRUE,
                ...)

            private$..subscale1 <- jmvcore::OptionVariables$new(
                "subscale1",
                subscale1,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..subscale2 <- jmvcore::OptionVariables$new(
                "subscale2",
                subscale2,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=250,
                min=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..sequential <- jmvcore::OptionBool$new(
                "sequential",
                sequential,
                default=FALSE)
            private$..minExpected <- jmvcore::OptionNumber$new(
                "minExpected",
                minExpected,
                default=0,
                min=0,
                max=100)

            self$.addOption(private$..subscale1)
            self$.addOption(private$..subscale2)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
            self$.addOption(private$..sequential)
            self$.addOption(private$..minExpected)
        }),
    active = list(
        subscale1 = function() private$..subscale1$value,
        subscale2 = function() private$..subscale2$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value,
        sequential = function() private$..sequential$value,
        minExpected = function() private$..minExpected$value),
    private = list(
        ..subscale1 = NA,
        ..subscale2 = NA,
        ..iterations = NA,
        ..seed = NA,
        ..sequential = NA,
        ..minExpected = NA)
)

martinlofResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "martinlofResults",
    inherit = jmvcore::Group,
    active = list(
        summaryTable = function() private$.items[["summaryTable"]],
        corrTable = function() private$.items[["corrTable"]],
        mlNote = function() private$.items[["mlNote"]],
        nullPlot = function() private$.items[["nullPlot"]],
        residualPlot = function() private$.items[["residualPlot"]],
        simCache = function() private$.items[["simCache"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Martin-Löf Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Martin-L\u00F6f Test of Unidimensionality",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "christensen2002",
                    "christensen2007",
                    "besag1991",
                    "zeileis2026",
                    "warm1989"),
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="corrTable",
                title="Subscale Correlation (WLE person estimates)",
                rows=1,
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed"),
                columns=list(
                    list(
                        `name`="r", 
                        `title`="Correlation", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciLow", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="ciHigh", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="mlNote",
                title="",
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="nullPlot",
                title="Monte Carlo Null Distribution",
                width=550,
                height=450,
                renderFun=".nullPlot",
                requiresData=TRUE,
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="residualPlot",
                title="Observed vs Expected Score Cross-Table Residuals",
                width=600,
                height=550,
                renderFun=".residualPlot",
                requiresData=TRUE,
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed",
                    "minExpected")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "subscale1",
                    "subscale2",
                    "iterations",
                    "sequential",
                    "seed")))}))

martinlofBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "martinlofBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "martinlof",
                version = c(1,0,0),
                options = options,
                results = martinlofResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Martin-Löf Test
#'
#' Martin-Löf likelihood-ratio test of unidimensionality against an
#' a priori partition of the items into two subscales, generalised
#' to polytomous Rasch / partial credit models (Christensen,
#' Bjorner, Kreiner & Petersen, 2002), computed by the easyRasch2 R
#' package (RMdimMartinLof()). The p-value is obtained by Monte
#' Carlo simulation under the unidimensional null model (Christensen
#' & Kreiner, 2007), because the asymptotic chi-square approximation
#' is biased toward conservatism at realistic sample sizes,
#' especially with polytomous items.
#' 
#' Interpreting the p-value: a small p-value means the observed
#' joint distribution of the two subscale scores departs from what a
#' single underlying dimension predicts -- evidence against
#' unidimensionality for this partition. Read it together with the
#' correlation between the subscale person estimates (WLE), which
#' serves as the effect size: a rejected test with a correlation
#' near 1 indicates a statistically detectable but trivial
#' departure, while a correlation clearly below 1 indicates
#' substantive multidimensionality.
#' 
#' Important: this is not a routine screening tool. The partition
#' must be specified a priori (e.g. from theory or instrument
#' design). Testing a partition suggested by the same data -- for
#' example the split indicated by the first residual PCA contrast --
#' inflates the Type-I error rate and invalidates the p-value.
#' 
#' The analysis uses complete cases only (rows with any missing
#' response are excluded; at least 30 complete cases are required).
#' Results are identical to easyRasch2::RMdimMartinLof() with the
#' same seed and iterations. Single-core sequential processing is
#' used.
#' 
#' @param data .
#' @param subscale1 .
#' @param subscale2 .
#' @param iterations .
#' @param seed .
#' @param sequential .
#' @param minExpected .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$corrTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mlNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$nullPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$residualPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simCache} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
martinlof <- function(
    data,
    subscale1,
    subscale2,
    iterations = 250,
    seed = 42,
    sequential = FALSE,
    minExpected = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("martinlof requires jmvcore to be installed (restart may be required)")

    if ( ! missing(subscale1)) subscale1 <- jmvcore::resolveQuo(jmvcore::enquo(subscale1))
    if ( ! missing(subscale2)) subscale2 <- jmvcore::resolveQuo(jmvcore::enquo(subscale2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(subscale1), subscale1, NULL),
            `if`( ! missing(subscale2), subscale2, NULL))


    options <- martinlofOptions$new(
        subscale1 = subscale1,
        subscale2 = subscale2,
        iterations = iterations,
        seed = seed,
        sequential = sequential,
        minExpected = minExpected)

    analysis <- martinlofClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

