
# This file is automatically generated, you probably don't want to edit this

partgamdifOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partgamdifOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            difVar = NULL,
            computeCutoff = FALSE,
            hdciWidth = 0.99,
            iterations = 250,
            seed = 42,
            sortByGamma = FALSE, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="partgamdif",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..difVar <- jmvcore::OptionVariable$new(
                "difVar",
                difVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..hdciWidth <- jmvcore::OptionNumber$new(
                "hdciWidth",
                hdciWidth,
                default=0.99,
                min=0.5,
                max=1)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=250,
                min=50)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..sortByGamma <- jmvcore::OptionBool$new(
                "sortByGamma",
                sortByGamma,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..difVar)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..hdciWidth)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
            self$.addOption(private$..sortByGamma)
        }),
    active = list(
        vars = function() private$..vars$value,
        difVar = function() private$..difVar$value,
        computeCutoff = function() private$..computeCutoff$value,
        hdciWidth = function() private$..hdciWidth$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value,
        sortByGamma = function() private$..sortByGamma$value),
    private = list(
        ..vars = NA,
        ..difVar = NA,
        ..computeCutoff = NA,
        ..hdciWidth = NA,
        ..iterations = NA,
        ..seed = NA,
        ..sortByGamma = NA)
)

partgamdifResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partgamdifResults",
    inherit = jmvcore::Group,
    active = list(
        pgdifTable = function() private$.items[["pgdifTable"]],
        cutoffNote = function() private$.items[["cutoffNote"]],
        pgdifPlot = function() private$.items[["pgdifPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Gamma DIF")
            self$add(jmvcore::Table$new(
                options=options,
                name="pgdifTable",
                title="Partial Gamma DIF",
                rows=0,
                clearWith=list(
                    "vars",
                    "difVar",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed",
                    "sortByGamma"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="gamma", 
                        `title`="Partial gamma", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="padjBH", 
                        `title`="Adjusted p (BH)", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="gammaLow", 
                        `title`="Gamma low", 
                        `type`="number", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="gammaHigh", 
                        `title`="Gamma high", 
                        `type`="number", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="cutoffNote",
                title="",
                visible="(computeCutoff)",
                clearWith=list(
                    "vars",
                    "difVar",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="pgdifPlot",
                title="Simulated Partial Gamma Distribution",
                width=400,
                height=500,
                renderFun=".pgDIFplot",
                visible="(computeCutoff)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "difVar",
                    "computeCutoff",
                    "hdciWidth",
                    "iterations",
                    "seed",
                    "sortByGamma")))}))

partgamdifBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partgamdifBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "partgamdif",
                version = c(1,0,0),
                options = options,
                results = partgamdifResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Partial Gamma DIF
#'
#' 
#' @param data .
#' @param vars .
#' @param difVar .
#' @param computeCutoff .
#' @param hdciWidth .
#' @param iterations .
#' @param seed .
#' @param sortByGamma .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$pgdifTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cutoffNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pgdifPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pgdifTable$asDF}
#'
#' \code{as.data.frame(results$pgdifTable)}
#'
#' @export
partgamdif <- function(
    data,
    vars,
    difVar,
    computeCutoff = FALSE,
    hdciWidth = 0.99,
    iterations = 250,
    seed = 42,
    sortByGamma = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("partgamdif requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(difVar)) difVar <- jmvcore::resolveQuo(jmvcore::enquo(difVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(difVar), difVar, NULL))


    options <- partgamdifOptions$new(
        vars = vars,
        difVar = difVar,
        computeCutoff = computeCutoff,
        hdciWidth = hdciWidth,
        iterations = iterations,
        seed = seed,
        sortByGamma = sortByGamma)

    analysis <- partgamdifClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

