
# This file is automatically generated, you probably don't want to edit this

personchangeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personchangeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars1 = NULL,
            vars2 = NULL,
            id = NULL,
            anchor = "stack",
            method = "WLE",
            nullType = "measurement",
            retestSd = 0.3,
            alpha = 0.05,
            direction = "two.sided",
            conditionalCrit = FALSE,
            showTable = FALSE,
            flaggedOnly = FALSE,
            estimateRetestSd = FALSE,
            retestIter = 500,
            retestBoot = TRUE,
            retestBootIter = 500,
            confInt = 95,
            seed = 42,
            thetaMin = -10,
            thetaMax = 10, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="personchange",
                requiresData=TRUE,
                ...)

            private$..vars1 <- jmvcore::OptionVariables$new(
                "vars1",
                vars1,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..vars2 <- jmvcore::OptionVariables$new(
                "vars2",
                vars2,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id,
                default=NULL,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..anchor <- jmvcore::OptionList$new(
                "anchor",
                anchor,
                options=list(
                    "stack",
                    "t1",
                    "t2"),
                default="stack")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "WLE",
                    "EAP"),
                default="WLE")
            private$..nullType <- jmvcore::OptionList$new(
                "nullType",
                nullType,
                options=list(
                    "measurement",
                    "retest"),
                default="measurement")
            private$..retestSd <- jmvcore::OptionNumber$new(
                "retestSd",
                retestSd,
                default=0.3,
                min=0.001,
                max=5)
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05,
                min=0.001,
                max=0.2)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    "two.sided",
                    "increase",
                    "decrease"),
                default="two.sided")
            private$..conditionalCrit <- jmvcore::OptionBool$new(
                "conditionalCrit",
                conditionalCrit,
                default=FALSE)
            private$..showTable <- jmvcore::OptionBool$new(
                "showTable",
                showTable,
                default=FALSE)
            private$..flaggedOnly <- jmvcore::OptionBool$new(
                "flaggedOnly",
                flaggedOnly,
                default=FALSE)
            private$..estimateRetestSd <- jmvcore::OptionBool$new(
                "estimateRetestSd",
                estimateRetestSd,
                default=FALSE)
            private$..retestIter <- jmvcore::OptionInteger$new(
                "retestIter",
                retestIter,
                default=500,
                min=50,
                max=5000)
            private$..retestBoot <- jmvcore::OptionBool$new(
                "retestBoot",
                retestBoot,
                default=TRUE)
            private$..retestBootIter <- jmvcore::OptionInteger$new(
                "retestBootIter",
                retestBootIter,
                default=500,
                min=50,
                max=5000)
            private$..confInt <- jmvcore::OptionNumber$new(
                "confInt",
                confInt,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..thetaMin <- jmvcore::OptionNumber$new(
                "thetaMin",
                thetaMin,
                default=-10,
                min=-20,
                max=0)
            private$..thetaMax <- jmvcore::OptionNumber$new(
                "thetaMax",
                thetaMax,
                default=10,
                min=0,
                max=20)
            private$..outputThetaT1 <- jmvcore::OptionOutput$new(
                "outputThetaT1")
            private$..outputThetaT2 <- jmvcore::OptionOutput$new(
                "outputThetaT2")
            private$..outputChange <- jmvcore::OptionOutput$new(
                "outputChange")
            private$..outputSeDiff <- jmvcore::OptionOutput$new(
                "outputSeDiff")
            private$..outputRci <- jmvcore::OptionOutput$new(
                "outputRci")
            private$..outputPValue <- jmvcore::OptionOutput$new(
                "outputPValue")
            private$..outputClass <- jmvcore::OptionOutput$new(
                "outputClass")

            self$.addOption(private$..vars1)
            self$.addOption(private$..vars2)
            self$.addOption(private$..id)
            self$.addOption(private$..anchor)
            self$.addOption(private$..method)
            self$.addOption(private$..nullType)
            self$.addOption(private$..retestSd)
            self$.addOption(private$..alpha)
            self$.addOption(private$..direction)
            self$.addOption(private$..conditionalCrit)
            self$.addOption(private$..showTable)
            self$.addOption(private$..flaggedOnly)
            self$.addOption(private$..estimateRetestSd)
            self$.addOption(private$..retestIter)
            self$.addOption(private$..retestBoot)
            self$.addOption(private$..retestBootIter)
            self$.addOption(private$..confInt)
            self$.addOption(private$..seed)
            self$.addOption(private$..thetaMin)
            self$.addOption(private$..thetaMax)
            self$.addOption(private$..outputThetaT1)
            self$.addOption(private$..outputThetaT2)
            self$.addOption(private$..outputChange)
            self$.addOption(private$..outputSeDiff)
            self$.addOption(private$..outputRci)
            self$.addOption(private$..outputPValue)
            self$.addOption(private$..outputClass)
        }),
    active = list(
        vars1 = function() private$..vars1$value,
        vars2 = function() private$..vars2$value,
        id = function() private$..id$value,
        anchor = function() private$..anchor$value,
        method = function() private$..method$value,
        nullType = function() private$..nullType$value,
        retestSd = function() private$..retestSd$value,
        alpha = function() private$..alpha$value,
        direction = function() private$..direction$value,
        conditionalCrit = function() private$..conditionalCrit$value,
        showTable = function() private$..showTable$value,
        flaggedOnly = function() private$..flaggedOnly$value,
        estimateRetestSd = function() private$..estimateRetestSd$value,
        retestIter = function() private$..retestIter$value,
        retestBoot = function() private$..retestBoot$value,
        retestBootIter = function() private$..retestBootIter$value,
        confInt = function() private$..confInt$value,
        seed = function() private$..seed$value,
        thetaMin = function() private$..thetaMin$value,
        thetaMax = function() private$..thetaMax$value,
        outputThetaT1 = function() private$..outputThetaT1$value,
        outputThetaT2 = function() private$..outputThetaT2$value,
        outputChange = function() private$..outputChange$value,
        outputSeDiff = function() private$..outputSeDiff$value,
        outputRci = function() private$..outputRci$value,
        outputPValue = function() private$..outputPValue$value,
        outputClass = function() private$..outputClass$value),
    private = list(
        ..vars1 = NA,
        ..vars2 = NA,
        ..id = NA,
        ..anchor = NA,
        ..method = NA,
        ..nullType = NA,
        ..retestSd = NA,
        ..alpha = NA,
        ..direction = NA,
        ..conditionalCrit = NA,
        ..showTable = NA,
        ..flaggedOnly = NA,
        ..estimateRetestSd = NA,
        ..retestIter = NA,
        ..retestBoot = NA,
        ..retestBootIter = NA,
        ..confInt = NA,
        ..seed = NA,
        ..thetaMin = NA,
        ..thetaMax = NA,
        ..outputThetaT1 = NA,
        ..outputThetaT2 = NA,
        ..outputChange = NA,
        ..outputSeDiff = NA,
        ..outputRci = NA,
        ..outputPValue = NA,
        ..outputClass = NA)
)

personchangeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personchangeResults",
    inherit = jmvcore::Group,
    active = list(
        pairingTable = function() private$.items[["pairingTable"]],
        changePlot = function() private$.items[["changePlot"]],
        summaryTable = function() private$.items[["summaryTable"]],
        critPlot = function() private$.items[["critPlot"]],
        changeTable = function() private$.items[["changeTable"]],
        retestTable = function() private$.items[["retestTable"]],
        retestCache = function() private$.items[["retestCache"]],
        changeCache = function() private$.items[["changeCache"]],
        changeNote = function() private$.items[["changeNote"]],
        outputThetaT1 = function() private$.items[["outputThetaT1"]],
        outputThetaT2 = function() private$.items[["outputThetaT2"]],
        outputChange = function() private$.items[["outputChange"]],
        outputSeDiff = function() private$.items[["outputSeDiff"]],
        outputRci = function() private$.items[["outputRci"]],
        outputPValue = function() private$.items[["outputPValue"]],
        outputClass = function() private$.items[["outputClass"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Person Change")
            self$add(jmvcore::Table$new(
                options=options,
                name="pairingTable",
                title="Item Pairing",
                rows="(vars1)",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2"),
                clearWith=list(
                    "vars1",
                    "vars2"),
                columns=list(
                    list(
                        `name`="pair", 
                        `title`="#", 
                        `type`="integer"),
                    list(
                        `name`="item1", 
                        `title`="Time 1", 
                        `type`="text"),
                    list(
                        `name`="item2", 
                        `title`="Time 2", 
                        `type`="text"),
                    list(
                        `name`="cats", 
                        `title`="Response categories", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="changePlot",
                title="Person Locations at the Two Occasions",
                width=600,
                height=550,
                renderFun=".changePlot",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "jacobsontruax1991",
                    "caronni2026",
                    "zumbo2026",
                    "warm1989",
                    "zeileis2026"),
                clearWith=list(
                    "vars1",
                    "vars2",
                    "id",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "estimateRetestSd",
                    "retestIter",
                    "seed",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Change Summary",
                rows=0,
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "estimateRetestSd",
                    "retestIter",
                    "seed",
                    "thetaMin",
                    "thetaMax"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="notes", 
                        `title`="Notes", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="critPlot",
                title="Critical Values Across the Scale",
                width=650,
                height=500,
                renderFun=".critPlot",
                visible="(conditionalCrit)",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "estimateRetestSd",
                    "retestIter",
                    "seed",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Table$new(
                options=options,
                name="changeTable",
                title="Per-Respondent Results",
                rows=0,
                visible="(showTable)",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "id",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "estimateRetestSd",
                    "retestIter",
                    "seed",
                    "thetaMin",
                    "thetaMax",
                    "flaggedOnly"),
                columns=list(
                    list(
                        `name`="id", 
                        `title`="ID", 
                        `type`="text"),
                    list(
                        `name`="sumT1", 
                        `title`="Sum", 
                        `type`="integer", 
                        `superTitle`="Time 1"),
                    list(
                        `name`="thetaT1", 
                        `title`="Theta", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Time 1"),
                    list(
                        `name`="sumT2", 
                        `title`="Sum", 
                        `type`="integer", 
                        `superTitle`="Time 2"),
                    list(
                        `name`="thetaT2", 
                        `title`="Theta", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Time 2"),
                    list(
                        `name`="change", 
                        `title`="Change", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="seDiff", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="rci", 
                        `title`="RCI", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pValue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="critLower", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Critical"),
                    list(
                        `name`="critUpper", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Critical"),
                    list(
                        `name`="changeClass", 
                        `title`="Classification", 
                        `type`="text"),
                    list(
                        `name`="retestTip", 
                        `title`="Retest SD tip", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="retestTable",
                title="Retest SD Estimated from These Data",
                rows=0,
                visible="(estimateRetestSd)",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2"),
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "retestIter",
                    "retestBoot",
                    "retestBootIter",
                    "confInt",
                    "seed",
                    "thetaMin",
                    "thetaMax"),
                columns=list(
                    list(
                        `name`="quantity", 
                        `title`="Quantity", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Interval"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `format`="zto", 
                        `superTitle`="Interval"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="retestCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "retestIter",
                    "retestBoot",
                    "retestBootIter",
                    "confInt",
                    "seed",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Html$new(
                options=options,
                name="changeCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars1",
                    "vars2",
                    "id",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Html$new(
                options=options,
                name="changeNote",
                title="",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "estimateRetestSd")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputThetaT1",
                title="Person location, time 1",
                varTitle="theta_t1",
                varDescription="Person location on the latent variable at occasion 1 (logits), from the easyRasch2jmv Person Change analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputThetaT2",
                title="Person location, time 2",
                varTitle="theta_t2",
                varDescription="Person location on the latent variable at occasion 2 (logits), from the easyRasch2jmv Person Change analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputChange",
                title="Change (logits)",
                varTitle="change",
                varDescription="Occasion 2 minus occasion 1 person location, in logits. This is the magnitude of change, from the easyRasch2jmv Person Change analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputSeDiff",
                title="SE of the change",
                varTitle="se_diff",
                varDescription="Standard error of the change (logits), from the easyRasch2jmv Person Change analysis. Depends on which null is in force.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputRci",
                title="Change index (RCI)",
                varTitle="rci",
                varDescription="Rasch change index, change divided by its standard error (unitless). A decision statistic, not a measure of how much a respondent changed: do not rank respondents by it. From the easyRasch2jmv Person Change analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputPValue",
                title="p-value",
                varTitle="p_change",
                varDescription="p-value for the change index against the enumerated null, from the easyRasch2jmv Person Change analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputClass",
                title="Change classification",
                varTitle="change_class",
                varDescription="Classification of each respondent as decrease, none detected, or increase, at the error rate in force. From the easyRasch2jmv Person Change analysis.\n",
                measureType="nominal",
                clearWith=list(
                    "vars1",
                    "vars2",
                    "anchor",
                    "method",
                    "nullType",
                    "retestSd",
                    "alpha",
                    "direction",
                    "conditionalCrit",
                    "thetaMin",
                    "thetaMax")))}))

personchangeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personchangeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "personchange",
                version = c(1,0,0),
                options = options,
                results = personchangeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Person Change
#'
#' Tests, for each respondent, whether their location on the latent
#' variable moved between two occasions by more than measurement
#' error allows, using the easyRasch2 R package
#' (RMpersonChange()). The statistic is the Rasch change index,
#' RCI = (theta2 - theta1) / SE_diff, referred to an exactly
#' enumerated null rather than to a normal distribution. Results
#' are identical to easyRasch2::RMpersonChange().
#' 
#' The two occasions are supplied as two sets of variables in the
#' same dataset, one row per respondent. **Items are paired by
#' their order in the two boxes**, not by name, so the first item
#' under Time 1 is matched with the first item under Time 2, and so
#' on. The pairing table above the figure shows which item was
#' matched with which, and should be checked before the results are
#' read. Data must be in wide format, with both occasions on the
#' same row.
#' 
#' Why not 1.96: the sum score is a sufficient statistic, so theta
#' takes only as many values as there are scores and its standard
#' error is a function of the score rather than a constant. A
#' respondent who moves to an extreme score produces a large change
#' and a large standard error together, which damps the ratio and
#' pulls both tails of the null inward. The critical value
#' therefore sits below 1.96, and further below on shorter scales.
#' Enumerating the null costs nothing here and needs no simulation,
#' no iterations and no random seed, so this analysis is
#' deterministic.
#' 
#' Read the change column for magnitude, in logits, and the change
#' index only for the decision. The index mixes how far a
#' respondent moved with how precisely each of their positions was
#' pinned down, so respondents must not be ranked by it.
#' 
#' @param data .
#' @param vars1 .
#' @param vars2 .
#' @param id .
#' @param anchor .
#' @param method .
#' @param nullType .
#' @param retestSd .
#' @param alpha .
#' @param direction .
#' @param conditionalCrit .
#' @param showTable .
#' @param flaggedOnly .
#' @param estimateRetestSd .
#' @param retestIter .
#' @param retestBoot .
#' @param retestBootIter .
#' @param confInt .
#' @param seed .
#' @param thetaMin .
#' @param thetaMax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$pairingTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$changePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$critPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$changeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$retestTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$retestCache} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$changeCache} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$changeNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outputThetaT1} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputThetaT2} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputChange} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputSeDiff} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputRci} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputPValue} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputClass} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pairingTable$asDF}
#'
#' \code{as.data.frame(results$pairingTable)}
#'
#' @export
personchange <- function(
    data,
    vars1,
    vars2,
    id = NULL,
    anchor = "stack",
    method = "WLE",
    nullType = "measurement",
    retestSd = 0.3,
    alpha = 0.05,
    direction = "two.sided",
    conditionalCrit = FALSE,
    showTable = FALSE,
    flaggedOnly = FALSE,
    estimateRetestSd = FALSE,
    retestIter = 500,
    retestBoot = TRUE,
    retestBootIter = 500,
    confInt = 95,
    seed = 42,
    thetaMin = -10,
    thetaMax = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("personchange requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars1)) vars1 <- jmvcore::resolveQuo(jmvcore::enquo(vars1))
    if ( ! missing(vars2)) vars2 <- jmvcore::resolveQuo(jmvcore::enquo(vars2))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars1), vars1, NULL),
            `if`( ! missing(vars2), vars2, NULL),
            `if`( ! missing(id), id, NULL))


    options <- personchangeOptions$new(
        vars1 = vars1,
        vars2 = vars2,
        id = id,
        anchor = anchor,
        method = method,
        nullType = nullType,
        retestSd = retestSd,
        alpha = alpha,
        direction = direction,
        conditionalCrit = conditionalCrit,
        showTable = showTable,
        flaggedOnly = flaggedOnly,
        estimateRetestSd = estimateRetestSd,
        retestIter = retestIter,
        retestBoot = retestBoot,
        retestBootIter = retestBootIter,
        confInt = confInt,
        seed = seed,
        thetaMin = thetaMin,
        thetaMax = thetaMax)

    analysis <- personchangeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

