
# This file is automatically generated, you probably don't want to edit this

personfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            statInfit = TRUE,
            statOutfit = TRUE,
            statLz = TRUE,
            flagDirection = "both",
            flagAlpha = 0.05,
            iterations = 500,
            seed = 42, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="personfit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..statInfit <- jmvcore::OptionBool$new(
                "statInfit",
                statInfit,
                default=TRUE)
            private$..statOutfit <- jmvcore::OptionBool$new(
                "statOutfit",
                statOutfit,
                default=TRUE)
            private$..statLz <- jmvcore::OptionBool$new(
                "statLz",
                statLz,
                default=TRUE)
            private$..flagDirection <- jmvcore::OptionList$new(
                "flagDirection",
                flagDirection,
                options=list(
                    "both",
                    "underfit"),
                default="both")
            private$..flagAlpha <- jmvcore::OptionNumber$new(
                "flagAlpha",
                flagAlpha,
                default=0.05,
                min=0.001,
                max=0.5)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=500,
                min=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)
            private$..outputFlagged <- jmvcore::OptionOutput$new(
                "outputFlagged")
            private$..outputInfit <- jmvcore::OptionOutput$new(
                "outputInfit")
            private$..outputOutfit <- jmvcore::OptionOutput$new(
                "outputOutfit")
            private$..outputLz <- jmvcore::OptionOutput$new(
                "outputLz")
            private$..outputPInfit <- jmvcore::OptionOutput$new(
                "outputPInfit")
            private$..outputPOutfit <- jmvcore::OptionOutput$new(
                "outputPOutfit")
            private$..outputPLz <- jmvcore::OptionOutput$new(
                "outputPLz")

            self$.addOption(private$..vars)
            self$.addOption(private$..statInfit)
            self$.addOption(private$..statOutfit)
            self$.addOption(private$..statLz)
            self$.addOption(private$..flagDirection)
            self$.addOption(private$..flagAlpha)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
            self$.addOption(private$..outputFlagged)
            self$.addOption(private$..outputInfit)
            self$.addOption(private$..outputOutfit)
            self$.addOption(private$..outputLz)
            self$.addOption(private$..outputPInfit)
            self$.addOption(private$..outputPOutfit)
            self$.addOption(private$..outputPLz)
        }),
    active = list(
        vars = function() private$..vars$value,
        statInfit = function() private$..statInfit$value,
        statOutfit = function() private$..statOutfit$value,
        statLz = function() private$..statLz$value,
        flagDirection = function() private$..flagDirection$value,
        flagAlpha = function() private$..flagAlpha$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value,
        outputFlagged = function() private$..outputFlagged$value,
        outputInfit = function() private$..outputInfit$value,
        outputOutfit = function() private$..outputOutfit$value,
        outputLz = function() private$..outputLz$value,
        outputPInfit = function() private$..outputPInfit$value,
        outputPOutfit = function() private$..outputPOutfit$value,
        outputPLz = function() private$..outputPLz$value),
    private = list(
        ..vars = NA,
        ..statInfit = NA,
        ..statOutfit = NA,
        ..statLz = NA,
        ..flagDirection = NA,
        ..flagAlpha = NA,
        ..iterations = NA,
        ..seed = NA,
        ..outputFlagged = NA,
        ..outputInfit = NA,
        ..outputOutfit = NA,
        ..outputLz = NA,
        ..outputPInfit = NA,
        ..outputPOutfit = NA,
        ..outputPLz = NA)
)

personfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personfitResults",
    inherit = jmvcore::Group,
    active = list(
        summaryTable = function() private$.items[["summaryTable"]],
        personfitNote = function() private$.items[["personfitNote"]],
        infitPlot = function() private$.items[["infitPlot"]],
        outfitPlot = function() private$.items[["outfitPlot"]],
        lzPlot = function() private$.items[["lzPlot"]],
        simCache = function() private$.items[["simCache"]],
        outputFlagged = function() private$.items[["outputFlagged"]],
        outputInfit = function() private$.items[["outputInfit"]],
        outputOutfit = function() private$.items[["outputOutfit"]],
        outputLz = function() private$.items[["outputLz"]],
        outputPInfit = function() private$.items[["outputPInfit"]],
        outputPOutfit = function() private$.items[["outputPOutfit"]],
        outputPLz = function() private$.items[["outputPLz"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Person Fit")
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Person Fit Summary",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "mueller2020",
                    "sinharay2016",
                    "kreiner2011",
                    "zeileis2026",
                    "warm1989"),
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="personfitNote",
                title="",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="infitPlot",
                title="Person Infit Map",
                width=550,
                height=450,
                renderFun=".infitMap",
                visible="(statInfit)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="outfitPlot",
                title="Person Outfit Map",
                width=550,
                height=450,
                renderFun=".outfitMap",
                visible="(statOutfit)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="lzPlot",
                title="Person lz Map",
                width=550,
                height=450,
                renderFun=".lzMap",
                visible="(statLz)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="simCache",
                title="",
                visible=FALSE,
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputFlagged",
                title="Flagged (any statistic)",
                varTitle="pfit_flagged",
                varDescription="1 when any requested person-fit statistic has an uncorrected resampled p-value below the flagging alpha (per-person screening flag), 0 otherwise; empty for extreme scorers, who cannot be assessed. From the easyRasch2jmv Person Fit analysis.\n",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputInfit",
                title="Infit MSQ",
                varTitle="pfit_infit",
                varDescription="Conditional person infit MSQ, from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputOutfit",
                title="Outfit MSQ",
                varTitle="pfit_outfit",
                varDescription="Conditional person outfit MSQ, from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputLz",
                title="lz",
                varTitle="pfit_lz",
                varDescription="Standardized log-likelihood person-fit statistic (lz), from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputPInfit",
                title="p-value (infit)",
                varTitle="pfit_p_infit",
                varDescription="Resampled p-value of the person infit MSQ, from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputPOutfit",
                title="p-value (outfit)",
                varTitle="pfit_p_outfit",
                varDescription="Resampled p-value of the person outfit MSQ, from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputPLz",
                title="p-value (lz)",
                varTitle="pfit_p_lz",
                varDescription="Resampled p-value of the person lz statistic, from the easyRasch2jmv Person Fit analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "statInfit",
                    "statOutfit",
                    "statLz",
                    "flagDirection",
                    "flagAlpha",
                    "iterations",
                    "seed")))}))

personfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "personfit",
                version = c(1,0,0),
                options = options,
                results = personfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Person Fit
#'
#' Computes per-respondent person-fit statistics with Monte-Carlo
#' resampled p-values, using the easyRasch2 R package
#' (RMpersonFit()): conditional infit and outfit mean-squares (MSQ;
#' computed conditional on the total score, so no biased person
#' estimate enters, and partial missingness is handled directly) and
#' the standardized log-likelihood statistic lz. Significance is
#' assessed by resampling under the fitted model rather than by the
#' unreliable asymptotic null distributions: the MSQ statistics are
#' referenced against patterns sampled conditional on the person's
#' total score, and lz against patterns simulated at the estimated
#' location with the location re-estimated per pattern. Results are
#' identical to easyRasch2::RMpersonFit() with the same seed and
#' iterations. Single-core sequential processing is used.
#' 
#' Each requested statistic is shown as a person-fit map (statistic
#' against person location, flagged respondents highlighted). A
#' respondent is flagged when the uncorrected p-value of any
#' requested statistic falls below the flagging alpha -- a
#' per-person screening flag, so under model fit about alpha of the
#' respondents are flagged by chance. Extreme scorers (minimum or
#' maximum possible score) cannot be assessed and receive no values.
#' 
#' The flag and the underlying statistics and p-values can be saved
#' as new variables in the dataset -- for example to filter out
#' aberrant respondents before rerunning other analyses.
#' 
#' @param data .
#' @param vars .
#' @param statInfit .
#' @param statOutfit .
#' @param statLz .
#' @param flagDirection .
#' @param flagAlpha .
#' @param iterations .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$personfitNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$infitPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$outfitPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$lzPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$simCache} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$outputFlagged} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputInfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputOutfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputLz} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputPInfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputPOutfit} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputPLz} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
personfit <- function(
    data,
    vars,
    statInfit = TRUE,
    statOutfit = TRUE,
    statLz = TRUE,
    flagDirection = "both",
    flagAlpha = 0.05,
    iterations = 500,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("personfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- personfitOptions$new(
        vars = vars,
        statInfit = statInfit,
        statOutfit = statOutfit,
        statLz = statLz,
        flagDirection = flagDirection,
        flagAlpha = flagAlpha,
        iterations = iterations,
        seed = seed)

    analysis <- personfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

