
# This file is automatically generated, you probably don't want to edit this

personparamsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personparamsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            method = "WLE",
            thetaMin = -10,
            thetaMax = 10,
            showScoreTable = FALSE,
            showFigure = FALSE,
            ciMultiplier = 1.96, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="personparams",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "WLE",
                    "EAP"),
                default="WLE")
            private$..thetaMin <- jmvcore::OptionNumber$new(
                "thetaMin",
                thetaMin,
                default=-10,
                min=-20,
                max=0)
            private$..thetaMax <- jmvcore::OptionNumber$new(
                "thetaMax",
                thetaMax,
                default=10,
                min=0,
                max=20)
            private$..showScoreTable <- jmvcore::OptionBool$new(
                "showScoreTable",
                showScoreTable,
                default=FALSE)
            private$..showFigure <- jmvcore::OptionBool$new(
                "showFigure",
                showFigure,
                default=FALSE)
            private$..ciMultiplier <- jmvcore::OptionNumber$new(
                "ciMultiplier",
                ciMultiplier,
                default=1.96,
                min=0.1,
                max=5)
            private$..outputTheta <- jmvcore::OptionOutput$new(
                "outputTheta")
            private$..outputSem <- jmvcore::OptionOutput$new(
                "outputSem")
            private$..outputSumScore <- jmvcore::OptionOutput$new(
                "outputSumScore")
            private$..outputNAnswered <- jmvcore::OptionOutput$new(
                "outputNAnswered")
            private$..outputExtreme <- jmvcore::OptionOutput$new(
                "outputExtreme")

            self$.addOption(private$..vars)
            self$.addOption(private$..method)
            self$.addOption(private$..thetaMin)
            self$.addOption(private$..thetaMax)
            self$.addOption(private$..showScoreTable)
            self$.addOption(private$..showFigure)
            self$.addOption(private$..ciMultiplier)
            self$.addOption(private$..outputTheta)
            self$.addOption(private$..outputSem)
            self$.addOption(private$..outputSumScore)
            self$.addOption(private$..outputNAnswered)
            self$.addOption(private$..outputExtreme)
        }),
    active = list(
        vars = function() private$..vars$value,
        method = function() private$..method$value,
        thetaMin = function() private$..thetaMin$value,
        thetaMax = function() private$..thetaMax$value,
        showScoreTable = function() private$..showScoreTable$value,
        showFigure = function() private$..showFigure$value,
        ciMultiplier = function() private$..ciMultiplier$value,
        outputTheta = function() private$..outputTheta$value,
        outputSem = function() private$..outputSem$value,
        outputSumScore = function() private$..outputSumScore$value,
        outputNAnswered = function() private$..outputNAnswered$value,
        outputExtreme = function() private$..outputExtreme$value),
    private = list(
        ..vars = NA,
        ..method = NA,
        ..thetaMin = NA,
        ..thetaMax = NA,
        ..showScoreTable = NA,
        ..showFigure = NA,
        ..ciMultiplier = NA,
        ..outputTheta = NA,
        ..outputSem = NA,
        ..outputSumScore = NA,
        ..outputNAnswered = NA,
        ..outputExtreme = NA)
)

personparamsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personparamsResults",
    inherit = jmvcore::Group,
    active = list(
        summaryTable = function() private$.items[["summaryTable"]],
        personNote = function() private$.items[["personNote"]],
        thetaPlot = function() private$.items[["thetaPlot"]],
        outputTheta = function() private$.items[["outputTheta"]],
        outputSem = function() private$.items[["outputSem"]],
        outputSumScore = function() private$.items[["outputSumScore"]],
        outputNAnswered = function() private$.items[["outputNAnswered"]],
        outputExtreme = function() private$.items[["outputExtreme"]],
        scoreTable = function() private$.items[["scoreTable"]],
        scorePlot = function() private$.items[["scorePlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Person Parameters")
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Person Location Summary",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "warm1989",
                    "bock1982",
                    "zeileis2026"),
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="personNote",
                title="",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Image$new(
                options=options,
                name="thetaPlot",
                title="Person Location Distribution",
                width=550,
                height=450,
                renderFun=".thetaPlot",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputTheta",
                title="Person location (theta)",
                varTitle="theta",
                varDescription="Person location on the latent variable (logits), estimated with easyRasch2 (jamovi module easyRasch2jmv, Person Parameters analysis).\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputSem",
                title="SE of measurement (SEM)",
                varTitle="SEM",
                varDescription="Standard error of measurement of the estimated person location (logits), from the easyRasch2jmv Person Parameters analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputSumScore",
                title="Sum score",
                varTitle="sum_score",
                varDescription="Sum score over the selected items (answered items only), from the easyRasch2jmv Person Parameters analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputNAnswered",
                title="Items answered",
                varTitle="n_answered",
                varDescription="Number of selected items with a non-missing response, from the easyRasch2jmv Person Parameters analysis.\n",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Output$new(
                options=options,
                name="outputExtreme",
                title="Extreme score (min or max)",
                varTitle="extreme",
                varDescription="1 when the respondent scored the minimum or maximum possible on the items they answered (person location extrapolated, large SEM), 0 otherwise. From the easyRasch2jmv Person Parameters analysis.\n",
                measureType="nominal",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable",
                title="Score-to-Theta Lookup",
                rows=0,
                visible="(showScoreTable)",
                refs=list(
                    "chalmers2012"),
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax"),
                columns=list(
                    list(
                        `name`="rawScore", 
                        `title`="Ordinal sum score", 
                        `type`="integer"),
                    list(
                        `name`="logitScore", 
                        `title`="Logit score", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="logitSE", 
                        `title`="Logit std.error", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="scorePlot",
                title="Sum Score to Logit Conversion",
                width=450,
                height=600,
                renderFun=".scorePlot",
                visible="(showScoreTable && showFigure)",
                clearWith=list(
                    "vars",
                    "method",
                    "ciMultiplier",
                    "thetaMin",
                    "thetaMax")))}))

personparamsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "personparamsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "personparams",
                version = c(1,0,0),
                options = options,
                results = personparamsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Person Parameters
#'
#' Estimates a location on the latent variable (theta, in logits) for
#' each respondent, with its standard error of measurement (SEM),
#' using the easyRasch2 R package (RMpersonParameters()): item
#' parameters are estimated once by conditional maximum likelihood
#' (CML, via psychotools) and treated as fixed; each person's theta
#' is then estimated from the items they answered, so respondents
#' with partially missing responses are retained. Results are
#' identical to easyRasch2::RMpersonParameters().
#' 
#' The estimates can be saved as new variables in the dataset (theta,
#' SEM, sum score, number of items answered, extreme-score flag) for
#' use in other jamovi analyses or for export.
#' 
#' A sum-score-to-logit lookup table (easyRasch2::RMscoreSE()) can
#' also be shown, mapping each possible raw sum score to a person
#' location and its standard error -- useful when reporting a
#' scale's measurement properties or converting raw totals to
#' interval-scaled scores -- with an optional figure.
#' 
#' WLE (Warm's weighted likelihood, the default) is bias-corrected
#' and yields finite locations for minimum and maximum scores, though
#' such extreme scores are extrapolated and carry large standard
#' errors. EAP (expected a posteriori) uses a normal prior estimated
#' from the data (marginal maximum likelihood, item parameters held
#' fixed) and shrinks extreme scores toward the prior mean.
#' 
#' @param data .
#' @param vars .
#' @param method .
#' @param thetaMin .
#' @param thetaMax .
#' @param showScoreTable .
#' @param showFigure .
#' @param ciMultiplier .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$personNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$thetaPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$outputTheta} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputSem} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputSumScore} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputNAnswered} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$outputExtreme} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$scoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scorePlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summaryTable$asDF}
#'
#' \code{as.data.frame(results$summaryTable)}
#'
#' @export
personparams <- function(
    data,
    vars,
    method = "WLE",
    thetaMin = -10,
    thetaMax = 10,
    showScoreTable = FALSE,
    showFigure = FALSE,
    ciMultiplier = 1.96) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("personparams requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- personparamsOptions$new(
        vars = vars,
        method = method,
        thetaMin = thetaMin,
        thetaMax = thetaMax,
        showScoreTable = showScoreTable,
        showFigure = showFigure,
        ciMultiplier = ciMultiplier)

    analysis <- personparamsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

