
# This file is automatically generated, you probably don't want to edit this

reliabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reliabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            estim = "WLE",
            draws = 1000,
            rmuIter = 50,
            confInt = 95,
            thetaMin = -10,
            thetaMax = 10,
            bootAlpha = FALSE,
            bootIter = 1000,
            seed = 42, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="reliability",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..estim <- jmvcore::OptionList$new(
                "estim",
                estim,
                options=list(
                    "WLE",
                    "EAP",
                    "MAP",
                    "ML"),
                default="WLE")
            private$..draws <- jmvcore::OptionInteger$new(
                "draws",
                draws,
                default=1000,
                min=100)
            private$..rmuIter <- jmvcore::OptionInteger$new(
                "rmuIter",
                rmuIter,
                default=50,
                min=5)
            private$..confInt <- jmvcore::OptionNumber$new(
                "confInt",
                confInt,
                default=95,
                min=50,
                max=99.9)
            private$..thetaMin <- jmvcore::OptionNumber$new(
                "thetaMin",
                thetaMin,
                default=-10,
                min=-20,
                max=0)
            private$..thetaMax <- jmvcore::OptionNumber$new(
                "thetaMax",
                thetaMax,
                default=10,
                min=0,
                max=20)
            private$..bootAlpha <- jmvcore::OptionBool$new(
                "bootAlpha",
                bootAlpha,
                default=FALSE)
            private$..bootIter <- jmvcore::OptionInteger$new(
                "bootIter",
                bootIter,
                default=1000,
                min=100)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)

            self$.addOption(private$..vars)
            self$.addOption(private$..estim)
            self$.addOption(private$..draws)
            self$.addOption(private$..rmuIter)
            self$.addOption(private$..confInt)
            self$.addOption(private$..thetaMin)
            self$.addOption(private$..thetaMax)
            self$.addOption(private$..bootAlpha)
            self$.addOption(private$..bootIter)
            self$.addOption(private$..seed)
        }),
    active = list(
        vars = function() private$..vars$value,
        estim = function() private$..estim$value,
        draws = function() private$..draws$value,
        rmuIter = function() private$..rmuIter$value,
        confInt = function() private$..confInt$value,
        thetaMin = function() private$..thetaMin$value,
        thetaMax = function() private$..thetaMax$value,
        bootAlpha = function() private$..bootAlpha$value,
        bootIter = function() private$..bootIter$value,
        seed = function() private$..seed$value),
    private = list(
        ..vars = NA,
        ..estim = NA,
        ..draws = NA,
        ..rmuIter = NA,
        ..confInt = NA,
        ..thetaMin = NA,
        ..thetaMax = NA,
        ..bootAlpha = NA,
        ..bootIter = NA,
        ..seed = NA)
)

reliabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reliabilityResults",
    inherit = jmvcore::Group,
    active = list(
        relTable = function() private$.items[["relTable"]],
        relNote = function() private$.items[["relNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Reliability")
            self$add(jmvcore::Table$new(
                options=options,
                name="relTable",
                title="Reliability Estimates",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "mair2007",
                    "chalmers2012",
                    "bignardi2025",
                    "mislevy1991",
                    "kay2025"),
                clearWith=list(
                    "vars",
                    "estim",
                    "draws",
                    "rmuIter",
                    "confInt",
                    "thetaMin",
                    "thetaMax",
                    "bootAlpha",
                    "bootIter",
                    "seed"),
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="HDCI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="HDCI"),
                    list(
                        `name`="notes", 
                        `title`="Notes", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="relNote",
                title="",
                clearWith=list(
                    "vars",
                    "estim",
                    "draws",
                    "rmuIter",
                    "confInt",
                    "thetaMin",
                    "thetaMax",
                    "bootAlpha",
                    "bootIter",
                    "seed")))}))

reliabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "reliabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "reliability",
                version = c(1,0,0),
                options = options,
                results = reliabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Reliability
#'
#' Reports four reliability indices for a Rasch / partial credit model:
#' Cronbach's alpha (closed-form), the Person Separation Index (PSI) via
#' eRm::SepRel(), empirical reliability via mirt::empirical_rxx(), and
#' Relative Measurement Uncertainty (RMU) computed from mirt plausible
#' values using the Bignardi, Kievit & Bürkner (2025) split-half
#' correlation method.
#' 
#' A non-parametric bootstrap CI can optionally be added for Cronbach's
#' alpha; bootstrapping is intentionally not offered for PSI / Empirical
#' in this Jamovi version because each iteration would require refitting
#' eRm and mirt and the cost makes it impractical inside the Jamovi UI
#' thread. Use the CLI function easyRasch2::RMreliability() for that.
#' 
#' @param data .
#' @param vars .
#' @param estim .
#' @param draws .
#' @param rmuIter .
#' @param confInt .
#' @param thetaMin .
#' @param thetaMax .
#' @param bootAlpha .
#' @param bootIter .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$relTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$relNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$relTable$asDF}
#'
#' \code{as.data.frame(results$relTable)}
#'
#' @export
reliability <- function(
    data,
    vars,
    estim = "WLE",
    draws = 1000,
    rmuIter = 50,
    confInt = 95,
    thetaMin = -10,
    thetaMax = 10,
    bootAlpha = FALSE,
    bootIter = 1000,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("reliability requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- reliabilityOptions$new(
        vars = vars,
        estim = estim,
        draws = draws,
        rmuIter = rmuIter,
        confInt = confInt,
        thetaMin = thetaMin,
        thetaMax = thetaMax,
        bootAlpha = bootAlpha,
        bootIter = bootIter,
        seed = seed)

    analysis <- reliabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

