
# This file is automatically generated, you probably don't want to edit this

residualpcaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "residualpcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nComponents = 3,
            coordFlip = FALSE,
            computeCutoff = FALSE,
            iterations = 250,
            seed = 42, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="residualpca",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..nComponents <- jmvcore::OptionInteger$new(
                "nComponents",
                nComponents,
                default=3,
                min=1,
                max=20)
            private$..coordFlip <- jmvcore::OptionBool$new(
                "coordFlip",
                coordFlip,
                default=FALSE)
            private$..computeCutoff <- jmvcore::OptionBool$new(
                "computeCutoff",
                computeCutoff,
                default=FALSE)
            private$..iterations <- jmvcore::OptionInteger$new(
                "iterations",
                iterations,
                default=250,
                min=50,
                max=5000)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42)

            self$.addOption(private$..vars)
            self$.addOption(private$..nComponents)
            self$.addOption(private$..coordFlip)
            self$.addOption(private$..computeCutoff)
            self$.addOption(private$..iterations)
            self$.addOption(private$..seed)
        }),
    active = list(
        vars = function() private$..vars$value,
        nComponents = function() private$..nComponents$value,
        coordFlip = function() private$..coordFlip$value,
        computeCutoff = function() private$..computeCutoff$value,
        iterations = function() private$..iterations$value,
        seed = function() private$..seed$value),
    private = list(
        ..vars = NA,
        ..nComponents = NA,
        ..coordFlip = NA,
        ..computeCutoff = NA,
        ..iterations = NA,
        ..seed = NA)
)

residualpcaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "residualpcaResults",
    inherit = jmvcore::Group,
    active = list(
        pcaTable = function() private$.items[["pcaTable"]],
        pcaNote = function() private$.items[["pcaNote"]],
        pcaPlot = function() private$.items[["pcaPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="PCA of Standardized Rasch Residuals")
            self$add(jmvcore::Table$new(
                options=options,
                name="pcaTable",
                title="Eigenvalues of Residual PCA",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "chou2010",
                    "mair2007"),
                clearWith=list(
                    "vars",
                    "nComponents",
                    "computeCutoff",
                    "iterations",
                    "seed"),
                columns=list(
                    list(
                        `name`="component", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="propVar", 
                        `title`="Prop. of unexplained var.", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cutoff", 
                        `title`="Cutoff (99th percentile)", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(computeCutoff)"),
                    list(
                        `name`="flagged", 
                        `title`="Flagged", 
                        `type`="text", 
                        `visible`="(computeCutoff)"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="pcaNote",
                title="",
                clearWith=list(
                    "vars",
                    "nComponents",
                    "computeCutoff",
                    "iterations",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="pcaPlot",
                title="PC1 Loadings vs Item Location",
                width=550,
                height=500,
                renderFun=".pcaPlot",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "coordFlip")))}))

residualpcaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "residualpcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "residualpca",
                version = c(1,0,0),
                options = options,
                results = residualpcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' PCA of Standardized Rasch Residuals
#'
#' Fits a Rasch model (RM for dichotomous data, PCM for polytomous --
#' chosen automatically) and runs an unrotated principal-component
#' analysis on the standardized residuals via \code{eRm::itemfit()} and
#' \code{stats::prcomp()}. Reports the largest eigenvalues, the proportion of
#' unexplained variance, and a loadings-vs-location plot for inspecting
#' the first residual contrast.
#' 
#' The "first contrast eigenvalue > 2" rule of thumb is unreliable: the
#' expected eigenvalue under a unidimensional model varies with sample
#' size, test length, and item-parameter spread. An optional
#' simulation-based critical value (Chou & Wang, 2010) compares the
#' observed eigenvalue against the 99th percentile of eigenvalues drawn
#' under the fitted unidimensional model.
#' 
#' @param data .
#' @param vars .
#' @param nComponents .
#' @param coordFlip .
#' @param computeCutoff .
#' @param iterations .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$pcaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pcaNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pcaPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$pcaTable$asDF}
#'
#' \code{as.data.frame(results$pcaTable)}
#'
#' @export
residualpca <- function(
    data,
    vars,
    nComponents = 3,
    coordFlip = FALSE,
    computeCutoff = FALSE,
    iterations = 250,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("residualpca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- residualpcaOptions$new(
        vars = vars,
        nComponents = nComponents,
        coordFlip = coordFlip,
        computeCutoff = computeCutoff,
        iterations = iterations,
        seed = seed)

    analysis <- residualpcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

