
# This file is automatically generated, you probably don't want to edit this

scoreseOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoreseOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            method = "WLE",
            thetaMin = -10,
            thetaMax = 10,
            showFigure = FALSE,
            ciMultiplier = 1.96, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="scorese",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "WLE",
                    "EAP"),
                default="WLE")
            private$..thetaMin <- jmvcore::OptionNumber$new(
                "thetaMin",
                thetaMin,
                default=-10,
                min=-20,
                max=0)
            private$..thetaMax <- jmvcore::OptionNumber$new(
                "thetaMax",
                thetaMax,
                default=10,
                min=0,
                max=20)
            private$..showFigure <- jmvcore::OptionBool$new(
                "showFigure",
                showFigure,
                default=FALSE)
            private$..ciMultiplier <- jmvcore::OptionNumber$new(
                "ciMultiplier",
                ciMultiplier,
                default=1.96,
                min=0.1,
                max=5)

            self$.addOption(private$..vars)
            self$.addOption(private$..method)
            self$.addOption(private$..thetaMin)
            self$.addOption(private$..thetaMax)
            self$.addOption(private$..showFigure)
            self$.addOption(private$..ciMultiplier)
        }),
    active = list(
        vars = function() private$..vars$value,
        method = function() private$..method$value,
        thetaMin = function() private$..thetaMin$value,
        thetaMax = function() private$..thetaMax$value,
        showFigure = function() private$..showFigure$value,
        ciMultiplier = function() private$..ciMultiplier$value),
    private = list(
        ..vars = NA,
        ..method = NA,
        ..thetaMin = NA,
        ..thetaMax = NA,
        ..showFigure = NA,
        ..ciMultiplier = NA)
)

scoreseResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoreseResults",
    inherit = jmvcore::Group,
    active = list(
        scoreTable = function() private$.items[["scoreTable"]],
        scoreNote = function() private$.items[["scoreNote"]],
        scorePlot = function() private$.items[["scorePlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sum Score to Logit Transformation")
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable",
                title="Score-to-Theta Lookup",
                rows=0,
                refs=list(
                    "easyRasch2jmv",
                    "warm1989",
                    "mair2007",
                    "chalmers2012",
                    "mueller2022"),
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax"),
                columns=list(
                    list(
                        `name`="rawScore", 
                        `title`="Ordinal sum score", 
                        `type`="integer"),
                    list(
                        `name`="logitScore", 
                        `title`="Logit score", 
                        `type`="number"),
                    list(
                        `name`="logitSE", 
                        `title`="Logit std.error", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="scoreNote",
                title="",
                clearWith=list(
                    "vars",
                    "method",
                    "thetaMin",
                    "thetaMax")))
            self$add(jmvcore::Image$new(
                options=options,
                name="scorePlot",
                title="Score Conversion",
                width=450,
                height=600,
                renderFun=".scorePlot",
                visible="(showFigure)",
                requiresData=TRUE,
                clearWith=list(
                    "vars",
                    "method",
                    "ciMultiplier",
                    "thetaMin",
                    "thetaMax")))}))

scoreseBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoreseBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "scorese",
                version = c(1,0,0),
                options = options,
                results = scoreseResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sum Score to Logit Transformation
#'
#' Maps each possible raw sum score to a person-location estimate (in
#' logits) and its standard error. Useful when reporting a scale's
#' measurement properties or converting raw totals to interval-scaled
#' scores.
#' 
#' Two estimation methods are available. WLE (default) fits the model
#' with eRm (CML) and applies Warm's Weighted Likelihood correction for
#' boundary-score bias. EAP fits the model with mirt (MML) and uses
#' sum-score-based Expected A Posteriori estimates with their posterior
#' SDs as standard errors. EAP estimates are finite at all score
#' boundaries (the prior shrinks them inward); WLE may yield Inf at
#' extremes when the boundary score cannot be solved within the
#' configured theta range.
#' 
#' @param data .
#' @param vars .
#' @param method .
#' @param thetaMin .
#' @param thetaMax .
#' @param showFigure .
#' @param ciMultiplier .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$scoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scoreNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$scorePlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$scoreTable$asDF}
#'
#' \code{as.data.frame(results$scoreTable)}
#'
#' @export
scorese <- function(
    data,
    vars,
    method = "WLE",
    thetaMin = -10,
    thetaMax = 10,
    showFigure = FALSE,
    ciMultiplier = 1.96) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scorese requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- scoreseOptions$new(
        vars = vars,
        method = method,
        thetaMin = thetaMin,
        thetaMax = thetaMax,
        showFigure = showFigure,
        ciMultiplier = ciMultiplier)

    analysis <- scoreseClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

