
# This file is automatically generated, you probably don't want to edit this

targetingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            robust = FALSE,
            sortItems = "data",
            bins = 15,
            xlimLow = -4,
            xlimHigh = 4,
            longFormat = FALSE,
            showCi = TRUE,
            ciLevel = 95,
            panel = "categories",
            categoryLabels = TRUE,
            rowGap = 1,
            viridisOption = "G",
            viridisBegin = 0.9,
            viridisEnd = 0.2, ...) {

            super$initialize(
                package="easyRasch2jmv",
                name="targeting",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=TRUE)
            private$..robust <- jmvcore::OptionBool$new(
                "robust",
                robust,
                default=FALSE)
            private$..sortItems <- jmvcore::OptionList$new(
                "sortItems",
                sortItems,
                options=list(
                    "data",
                    "location"),
                default="data")
            private$..bins <- jmvcore::OptionInteger$new(
                "bins",
                bins,
                default=15,
                min=5)
            private$..xlimLow <- jmvcore::OptionNumber$new(
                "xlimLow",
                xlimLow,
                default=-4,
                min=-10,
                max=0)
            private$..xlimHigh <- jmvcore::OptionNumber$new(
                "xlimHigh",
                xlimHigh,
                default=4,
                min=0,
                max=10)
            private$..longFormat <- jmvcore::OptionBool$new(
                "longFormat",
                longFormat,
                default=FALSE)
            private$..showCi <- jmvcore::OptionBool$new(
                "showCi",
                showCi,
                default=TRUE)
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                default=95,
                min=50,
                max=99.9)
            private$..panel <- jmvcore::OptionList$new(
                "panel",
                panel,
                options=list(
                    "categories",
                    "thresholds"),
                default="categories")
            private$..categoryLabels <- jmvcore::OptionBool$new(
                "categoryLabels",
                categoryLabels,
                default=TRUE)
            private$..rowGap <- jmvcore::OptionNumber$new(
                "rowGap",
                rowGap,
                default=1,
                min=0.8,
                max=2)
            private$..viridisOption <- jmvcore::OptionList$new(
                "viridisOption",
                viridisOption,
                options=list(
                    "G",
                    "D",
                    "E",
                    "F"),
                default="G")
            private$..viridisBegin <- jmvcore::OptionNumber$new(
                "viridisBegin",
                viridisBegin,
                default=0.9,
                min=0,
                max=1)
            private$..viridisEnd <- jmvcore::OptionNumber$new(
                "viridisEnd",
                viridisEnd,
                default=0.2,
                min=0,
                max=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..robust)
            self$.addOption(private$..sortItems)
            self$.addOption(private$..bins)
            self$.addOption(private$..xlimLow)
            self$.addOption(private$..xlimHigh)
            self$.addOption(private$..longFormat)
            self$.addOption(private$..showCi)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..panel)
            self$.addOption(private$..categoryLabels)
            self$.addOption(private$..rowGap)
            self$.addOption(private$..viridisOption)
            self$.addOption(private$..viridisBegin)
            self$.addOption(private$..viridisEnd)
        }),
    active = list(
        vars = function() private$..vars$value,
        robust = function() private$..robust$value,
        sortItems = function() private$..sortItems$value,
        bins = function() private$..bins$value,
        xlimLow = function() private$..xlimLow$value,
        xlimHigh = function() private$..xlimHigh$value,
        longFormat = function() private$..longFormat$value,
        showCi = function() private$..showCi$value,
        ciLevel = function() private$..ciLevel$value,
        panel = function() private$..panel$value,
        categoryLabels = function() private$..categoryLabels$value,
        rowGap = function() private$..rowGap$value,
        viridisOption = function() private$..viridisOption$value,
        viridisBegin = function() private$..viridisBegin$value,
        viridisEnd = function() private$..viridisEnd$value),
    private = list(
        ..vars = NA,
        ..robust = NA,
        ..sortItems = NA,
        ..bins = NA,
        ..xlimLow = NA,
        ..xlimHigh = NA,
        ..longFormat = NA,
        ..showCi = NA,
        ..ciLevel = NA,
        ..panel = NA,
        ..categoryLabels = NA,
        ..rowGap = NA,
        ..viridisOption = NA,
        ..viridisBegin = NA,
        ..viridisEnd = NA)
)

targetingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetingResults",
    inherit = jmvcore::Group,
    active = list(
        targetingPlot = function() private$.items[["targetingPlot"]],
        thresholdTable = function() private$.items[["thresholdTable"]],
        targetingNote = function() private$.items[["targetingNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Targeting Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="targetingPlot",
                title="Person-Item Targeting Plot",
                refs=list(
                    "easyRasch2jmv",
                    "easyRasch2",
                    "wright1979",
                    "zeileis2026",
                    "warm1989"),
                width=700,
                height=700,
                renderFun=".targetingPlot",
                clearWith=list(
                    "vars",
                    "panel",
                    "robust",
                    "sortItems",
                    "bins",
                    "xlimLow",
                    "xlimHigh",
                    "showCi",
                    "ciLevel",
                    "categoryLabels",
                    "rowGap",
                    "viridisOption",
                    "viridisBegin",
                    "viridisEnd")))
            self$add(jmvcore::Table$new(
                options=options,
                name="thresholdTable",
                title="Item Threshold Locations",
                rows=0,
                clearWith=list(
                    "vars",
                    "ciLevel",
                    "longFormat"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="targetingNote",
                title="",
                clearWith=list(
                    "vars",
                    "panel",
                    "categoryLabels")))}))

targetingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "easyRasch2jmv",
                name = "targeting",
                version = c(1,0,0),
                options = options,
                results = targetingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Targeting Plot
#'
#' Person-item targeting plot (Wright map): back-to-back histograms
#' of person locations and item threshold locations, above a bottom
#' panel showing where each response category is the most likely
#' answer, drawn by the easyRasch2 R package. Item thresholds are
#' estimated with CML (psychotools); when any response category has
#' fewer than 3 observations the analysis falls back to MML (mirt),
#' which is more numerically stable under sparse categories. Person
#' locations are weighted likelihood estimates (WLE), finite at
#' extreme scores. Results are identical to
#' easyRasch2::RMtargeting() and the threshold table to
#' easyRasch2::RMitemParameters().
#' 
#' The bottom panel draws each item as a bar partitioned into
#' response-category bands, with the threshold estimates and their
#' confidence intervals as a coloured row beneath it. Categories
#' that are never the most likely response, and thresholds that are
#' disordered relative to the category scores, are marked in red.
#' The previous dot-and-whisker panel of item thresholds remains
#' available.
#' 
#' @param data .
#' @param vars .
#' @param robust .
#' @param sortItems .
#' @param bins .
#' @param xlimLow .
#' @param xlimHigh .
#' @param longFormat .
#' @param showCi .
#' @param ciLevel .
#' @param panel .
#' @param categoryLabels .
#' @param rowGap .
#' @param viridisOption .
#' @param viridisBegin .
#' @param viridisEnd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$targetingPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$thresholdTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$targetingNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$thresholdTable$asDF}
#'
#' \code{as.data.frame(results$thresholdTable)}
#'
#' @export
targeting <- function(
    data,
    vars,
    robust = FALSE,
    sortItems = "data",
    bins = 15,
    xlimLow = -4,
    xlimHigh = 4,
    longFormat = FALSE,
    showCi = TRUE,
    ciLevel = 95,
    panel = "categories",
    categoryLabels = TRUE,
    rowGap = 1,
    viridisOption = "G",
    viridisBegin = 0.9,
    viridisEnd = 0.2) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("targeting requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- targetingOptions$new(
        vars = vars,
        robust = robust,
        sortItems = sortItems,
        bins = bins,
        xlimLow = xlimLow,
        xlimHigh = xlimHigh,
        longFormat = longFormat,
        showCi = showCi,
        ciLevel = ciLevel,
        panel = panel,
        categoryLabels = categoryLabels,
        rowGap = rowGap,
        viridisOption = viridisOption,
        viridisBegin = viridisBegin,
        viridisEnd = viridisEnd)

    analysis <- targetingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

